### ISSUE TITLE
Documentation: "Data Size Determination" off by one

### ISSUE THREAD

**Issue by jamesbowman** [ARM-software/astc-encoder#12]
In section 3.16 "Data Size Determination", the sample code has the line:

```
config_bits = 24 + 3*num_partitions;
```

but referring to table 15 "Table 15 –Multi-Partition Color Endpoint Modes" shows that there are 25 bits of data in locations `24:0`, so the line should be:

```
config_bits = 25 + 3*num_partitions;
```

**Comment by solidpixel** [comment]
Closing this one as a "won't fix".

The latest documentation is the Khronos extension specifications - the legacy PDF is out of date an includes other inaccuracies, so we're just going to remove it in #43 . 

For the latest specification please see:

* https://www.khronos.org/registry/OpenGL/extensions/OES/OES_texture_compression_astc.txt
