### ISSUE TITLE
Can no longer build v2.0 beta under macOS because of missing malloc.h

### ISSUE THREAD

**Issue by renaudbedard** [ARM-software/astc-encoder#128]
When attempting to build the latest source at this commit : https://github.com/ARM-software/astc-encoder/commit/77c80ce63340632926729cf66e904f6cfeae3c69

On macOS Mojave 10.14.6, I had the following error :

```
$ make batchbuild
[C++] stb_image.h
[C++] stb_image_write.h
[C++] tinyexr.h
In file included from /Users/rbedard/Documents/GitHub/astc-encoder/Source/astcenc_averages_and_directions.cpp:22:
/Users/rbedard/Documents/GitHub/astc-encoder/Source/astcenc_internal.h:30:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^~~~~~~~~~
1 error generated.
make[1]: *** [astcenc_averages_and_directions-nointrin.o] Error 1
make: *** [batchbuild] Error 2
```

I was able to fix it by changing the <malloc.h> include to <stdlib.h>, but I'm not sure if this fix is viable.

**Comment by solidpixel** [comment]
Thanks for the bug report. Which compiler are you using?
