### ISSUE TITLE
Hard-to-read tables and figures in the documentation when in dark mode

### ISSUE THREAD

**Issue by kubouch** [ARM-software/astc-encoder#138]
I noticed when using GitHub with a dark mode Chrome plugin, some figures in [the documentation](https://github.com/ARM-software/astc-encoder/blob/master/Docs/FormatOverview.md) are quite hard to read---see the screenshot. Especially the tables. Not sure if it's worth the effort fixing it---I can also open the tables separately in a new tab---but I thought I'd let you know at least.

![astc_dark_mode_table](https://user-images.githubusercontent.com/25571562/88297754-fb6eda80-cd08-11ea-9c51-d9414556853e.png)

**Comment by solidpixel** [comment]
Thanks - will take a  look. I will probably just replace the tables with simple Markdown versions; they don't really need to be images at all.

**Comment by kubouch** [comment]
Some labels in the axes and pictures were also quite hard to read - basically anything that's dark.

For reference, I used this plugin for the screenshot: https://chrome.google.com/webstore/detail/github-dark-theme/odkdlljoangmamjilkamahebpkgpeacp
Now I switched to https://github.com/StylishThemes/Github-Dark which makes some labels look better and some worse:
![astc_dark_mode_figure](https://user-images.githubusercontent.com/25571562/88299283-dc714800-cd0a-11ea-994e-0923a78da070.png)

**Comment by solidpixel** [comment]
Should now be fixed on master; all images have an explicit background color and tables are just markdown.
