### ISSUE TITLE
Is there a way to know original image was RGB vs RGBA?

### ISSUE THREAD

**Issue by thomasflynn** [ARM-software/astc-encoder#14]
I need to sort opaque and transparent/translucent objects differently (front-to-back vs back-to-front).  I understand that ASTC decodes to RGBA, but if the original source was RGB, then I know I can treat that object as an opaque object. 

I see in astc_codec_internals.h there is an enumeration of endpoint_formats (LUMINANCE, LUMINANCE_ALPHA, RGB, RGBA, etc.) that looks like it could tell me what i'm looking for.  Is this stored in the file anywhere?  It would not be optimal for the GPU to treat all objects as transparent and sort them back-to-front even if they were really opaque.  But without further info, I'm not sure what else to do.

hints?

**Comment by solidpixel** [comment]
No, this isn't possible via something simple like a header look up. The color endpoint format may vary on a per-block basis in the compressed, so to determine this you'd have to read the entire file and decode all blocks.

**Comment by gearvrf** [comment]
Yeah, parsing all the endpoints is what i ended up doing.  Slows down loading of the file, but then i at least have the information i need.  please keep this need in mind when designing future iterations of this format or other formats in the future.

**Comment by face2d** [comment]
use KTX container format instead. here's astc header:
```
typedef struct __attribute__((packed))
{
    uint8_t magic[4];
    uint8_t blockDimX;
    uint8_t blockDimY;
    uint8_t blockDimZ;
    uint8_t xSize[3];
    uint8_t ySize[3];
    uint8_t zSize[3];
} astc_header;
```

and here's ktx header:
```
typedef struct __attribute__((packed))
{
    uint8_t identifier[12];
    uint32_t endianness;
    uint32_t glType;
    uint32_t glTypeSize;
    uint32_t glFormat;
    uint32_t glInternalFormat;
    uint32_t glBaseInternalFormat;
    uint32_t pixelWidth;
    uint32_t pixelHeight;
    uint32_t pixelDepth;
    uint32_t arrayElementCount;
    uint32_t faceCount;
    uint32_t mipmapLevelCount;
    uint32_t keyValueDataLength;
} ktx_header;
```

Note, astc is an encoding, also is a file format.
KTX is a container format it can contains various of pixel format such as astc.
you can use ktx container to store astc content. original format is in it's header (`glFormat `, `glInternalFormat `, `glBaseInternalFormat `)

**Comment by solidpixel** [comment]
Closing - original question was answered.
