### ISSUE TITLE
Support CMake installation

### ISSUE THREAD

**Issue by rovedit** [ARM-software/astc-encoder#140]
**Context:** I'm currently working on a cross-platform project for my bachelors thesis in a CMake environment and plan to use astc-encoder as a library in my code. For dependency-management I use the vcpkg package manager.

**Problem:** As only a Makefile is provided and to integrate this code into my projects environment, I need to generate a suiting CMakeLists.txt for the project myself. This impacts the ease of use for people in a CMake environment.

**Possible Solution:** Since CMake supports the features of a Makefile and is mostly overall standard I would propose to create a CMakeLists.txt which does the job instead.

**Comment by solidpixel** [comment]
Happy to migrate at some point - it would be  nicer way of supporting multiple operating systems than manually having to maintain the VS 2019 project files. It's not going to happen for the 2.0 release though.

**Comment by solidpixel** [comment]
The latest master release has switched to CMake, albeit it's still a monolithic build of CLI+codec as a single executable. We're planning on splitting these at some point, but it's not the current priority.
