### ISSUE TITLE
Released binaries should be signed for macOS

### ISSUE THREAD

**Issue by alecazam** [ARM-software/astc-encoder#142]
To get these executables to launch on macOS 10.15.6, they must first be set to chmod 755 on them.  Then they must be opened from the command line with cmd+held to add a security execption checks on macOS.  

Just requesting the appropriate permission change on these.

**Comment by solidpixel** [comment]
Thanks for the bug report. They have executable permissions when we build them, so either it's getting lost in our packaging process or Catalina security policy is stripping it when downloading the files.

**Comment by solidpixel** [comment]
Looks like this is being done on the client side when downloading the binaries; they are executable if you download and unzip the macOS bundle in Linux.

To fix this one properly we'll need to set up code signing and notarization on the macOS build slave, etc - will look into this for 2.1.

**Comment by solidpixel** [comment]
Steps needed:

- [ ] Code sign the individual binaries using the signing service.
- [ ] Package all signed binaries in a simple .zip file.
- [ ] Upload the ZIP to the notarisation service.

It is not currently possible to staple notarisation result tickets to individual mach-o binaries, so notarization will rely on Gatekeeper having a live internet connection on the user machine. Given users are downloading from GitHub this doesn't seem too difficult.  

Signing and notarisation are slow, so this should only be done on the weekly release pipeline Jenkins job. Signing process is Arm-specific so this should handled as a post-process step outside of CMake.

**Comment by solidpixel** [comment]
Fixed on master; will get picked up by the next release.
