### ISSUE TITLE
astcenc 2.0 seems to have broken PVRTexToolCLI

### ISSUE THREAD

**Issue by alecazam** [ARM-software/astc-encoder#143]
I use this tool as a wrapper to astcenc, since astcenc used to only export to astc format.   Very happy about new KTX support, but when I replace astcenc with a renamed version of asctenc-avx2 version in my path, then I get encoding errors from PVRTexToolCLI.   Maybe some command line options were changed and broke this compression tool.  I'll try to post more here about errors.  I don't think this is a permission problem as mentioned in my earlier Github issue.

**Comment by solidpixel** [comment]
The command line has definitely changed in 2.0 - we were getting quite a few complaints around the esoteric and non-orthogonal parameters needed for some compression types (in particular HDR compression).

Given this was a major version change for the first time in 7 years this was a bit of a "one chance to do it". It will stay stable for future 2.x series releases.

**Comment by solidpixel** [comment]
Given the issue seems to be due to the command line changes I'm rejecting this one; PVRTexToolCLI will need to update their integration if they want to support 2.0.
