### ISSUE TITLE
Offer normal compression with gggr swizzle

### ISSUE THREAD

**Issue by alecazam** [ARM-software/astc-encoder#144]
This -normal mode of swizzling doesn't lineup with another way to swizzle BC1nm, BC3nm, A8L8.   Those can use gggr and a .ag swizzle where rb are stored constant across the block or repeats of ggg (to get L+A).  -normal uses rrrg with .ga swizzle.   I'm assuming this can be achieved with the post swizzle argument, but it might be good to offer another normal option for that form.  

I've also never seen anything using XY+Z mode of ASTC, so this seems like a wasted bit in the format.  Nothing else equivalent out there in other compressed formats I suppose.

-normal
           The input texture is a three channel normal map, storing unit
           length normals as R=X, G=Y, and B=Z, optimized for angular PSNR.
           The compressor will compress this data as a two channel X+Y
           normal map with the following channel layout (RGB=X, A=Y). The
           Z component can be recovered programatically in shader core by
           using the equation:

               Z = sqrt(1 - X^2 - Y^2).

**Comment by solidpixel** [comment]
> I'm assuming this can be achieved with the post swizzle argument

For normal channel selection and ordering, it's always been possible to select any pair of channels in any order by adding a custom encoding swizzle. For example, in you case you would want `-normal -esw gggr`.

I'm not convinced that single command convenience option is really required; adding more of them tends to make the command line harder to learn.

> I've also never seen anything using XY+Z mode of ASTC, so this seems like a wasted bit in the format.

I'm not entirely sure what you mean here. 

ASTC itself doesn't really care about X+Y or XY+Z. From the format point of view they are just two color (LA) or three color (RGB) endpoints with an optional second weight plane for non-correlated channels. Nothing about the actual data encoding is specifically related to storing normal data; the only thing that knows about normals is the compressor heuristics.

XY+Z is just a three color endpoint, with one channel assigned to a separate weight plane. I can assure you that the three color endpoints are used extensively for compressing RGB color data.

**Comment by alecazam** [comment]
> For example, in your case you would want -normal -esw gggr.

Thanks, just making sure that option was still there.

> I'm not entirely sure what you mean here.

XY+Z is mentioned as mode in the Wikipedia article on ASTC.  Must like you say, just be RGB+A mode, but it's indicated as one way to compress normals there.

**Comment by solidpixel** [comment]
Closing. All questions answered.
