### ISSUE TITLE
ASTCENC_TYPE_F32 is defined as enum, but unsupported in fetch_imageblock

### ISSUE THREAD

**Issue by alecazam** [ARM-software/astc-encoder#160]
Why is this ASTCENC_TYPE_F32 in astcenc.h defined when read/writes don't support it?  It looks like all inputs to the encoder convert to a float4 anyways, so this seems like the easiest path to import.

ASTCENC_TYPE_F32

code like this indicates that it's not a passthrough either.

```
void fetch_imageblock(...) 
{
if (img.data_type == ASTCENC_TYPE_U8)
else // if (img.data_type == ASTCENC_TYPE_F16)
	{
		assert(img.data_type == ASTCENC_TYPE_F16);
```

**Comment by solidpixel** [comment]
Yes, planned for the new image API. Will get covered as part of #161 .

**Comment by alecazam** [comment]
This involves another change, since it looks like one of the variance calcs is going back to data8/data16 values on the source, and doing another conversion to float (and not supporting fp32 input).  I'll try to supply that change here when I have a chance.
