### ISSUE TITLE
Two channel normal map encoding not reliably selecting LA encodings

### ISSUE THREAD

**Issue by solidpixel** [ARM-software/astc-encoder#172]
For a simple 8-bit normal map, I'm finding astcenc doesn't use dual-plane.  It also encodes some of the blocks as FMT_RGBA instead of FMT_LUMINANCE_ALPHA.   The reason seems to be floating point error introduced in all the math the encoder does.  I don't even see rounding on some of the numerical conversions.   I'm feeding in all data as floating point rgba/255.0f directly to the encoder, but the existing U8 and U16 paths did the exact same math.

This is the test normal map (taken from some old Id compression papers).

![collectorbarrel-n](https://user-images.githubusercontent.com/3750359/97752718-cf09ed80-1ab1-11eb-9523-8d26552f7d47.png)

_Originally posted by @alecazam in https://github.com/ARM-software/astc-encoder/issues/163#issuecomment-719771600_

**Comment by alecazam** [comment]
This is a screenshot of endpoint values in Xcode when the encode path uses FMT_RGBA instead of LA.

![image](https://user-images.githubusercontent.com/3750359/97753344-d1b91280-1ab2-11eb-98ea-8174f9b0691c.png)

**Comment by alecazam** [comment]
I take the original image (all 8-bit), swizzle it myself to gggr (same as rrrg), and then pass it through the astcenc encoder with weights of 1.0, 0.0, 0.0, 1.0.   I tried adding rounding to this routine, and all pixels now take that roundf() path (I didn't snap the lns) path, but the above block still takes the wrong path.  

```
// helper function to initialize the work-data from the orig-data
void imageblock_initialize_work_from_orig(
	imageblock* pb,
	int pixelcount
) {
    
#define DO_ROUND 1
#if DO_ROUND
    #define ROUND(x) roundf(x)
#else
    #define ROUND(x) x
#endif
    
    float *fptr = pb->orig_data;
	for (int i = 0; i < pixelcount; i++)
	{
		if (pb->rgb_lns[i] && pb->alpha_lns[i])
		{
			pb->data_r[i] = float_to_lns(fptr[0]);
			pb->data_g[i] = float_to_lns(fptr[1]);
			pb->data_b[i] = float_to_lns(fptr[2]);
            pb->data_a[i] = float_to_lns(fptr[3]);
		}
		else if (!(pb->rgb_lns[i] && pb->alpha_lns[i]))
		{
			pb->data_r[i] = ROUND(fptr[0] * 65535.0f);
			pb->data_g[i] = ROUND(fptr[1] * 65535.0f);
			pb->data_b[i] = ROUND(fptr[2] * 65535.0f);
            pb->data_a[i] = ROUND(fptr[3] * 65535.0f);
		}
        else if (pb->rgb_lns[i])
        {
            pb->data_r[i] = float_to_lns(fptr[0]);
            pb->data_g[i] = float_to_lns(fptr[1]);
            pb->data_b[i] = float_to_lns(fptr[2]);
            pb->data_a[i] = ROUND(fptr[3] * 65535.0f);
        }
		else if (pb->alpha_lns[i])
		{
            pb->data_r[i] = ROUND(fptr[0] * 65535.0f);
            pb->data_g[i] = ROUND(fptr[1] * 65535.0f);
            pb->data_b[i] = ROUND(fptr[2] * 65535.0f);
			pb->data_a[i] = float_to_lns(fptr[3]);
		}
		

		fptr += 4;
	}
}
```

**Comment by solidpixel** [comment]
This function is really before the compressor does anything, not surprised that this doesn't help. You really want it done as late as possible (perhaps in the endpoint encoding function). Would be good to root cause it though, that feels like a hack =)

**Comment by alecazam** [comment]
I tried some things later in the pipe, but also those didn't work.  It's a very deep encoder unlike some of the others that I work with.

Also the reason that I found this is that I was using encoders from ATE and astcenc, and noting that dual plane wasn't reported by either using astcenc decode.

**Comment by solidpixel** [comment]
For diagnostic testing - this patch forces it (breaks everything else):

```
diff --git a/Source/astcenc_pick_best_endpoint_format.cpp b/Source/astcenc_pick_best_endpoint_format.cpp
index 0de2f8b..bfe3859 100644
--- a/Source/astcenc_pick_best_endpoint_format.cpp
+++ b/Source/astcenc_pick_best_endpoint_format.cpp
@@ -335,7 +335,7 @@ static void compute_color_error_for_every_integer_count_and_quantization_level(
                        full_ldr_rgba_error += rgb_range_error + alpha_range_error;
 
                        best_error[i][3] = full_ldr_rgba_error;
-                       format_of_choice[i][3] = FMT_RGBA;
+                       format_of_choice[i][3] = FMT_LUMINANCE_ALPHA;
 
                        // for 6 integers, we have:
                        // - an LDR-RGB encoding
```

I've confirmed it removes the use of RGBA blocks, but it actually seem to reduce PSNR it in all of my test images here, although it's very marginal, so the codec seems to be doing the right thing. ASTC can have some weird interactions like this, due to the non-linear effects of the quantization error. 

It still might be worth chasing down as an optimization opportunity - the codec currently does a pile of maths to determine "best approach". We could just force LA or L, and skip the RGBA and RGB, given the difference in PSNR is small.

**Comment by alecazam** [comment]
I guess I don't understand dual-plane normal map encoding then.  I get that ASTC is this uber flexible format that can handle many different kinds of blocks, and uses a lot of silicon to do so.  I thought dual-plane was a decision across the entire image, and with L and LA and RGBScale mixed in there, maybe the image then can't pick dual-plane.  But if it was L1 and LA, then it could.  That would cut the endpoint storage down to 1 or 2 bytes per endpoint, and then more data for quality would be dedicated to partitioning schemes.  It does seem a lot like a mask to say, incoming data is known to be L or LA, so mask out the work done for rgb/a.  ETC and BC all have dedicated compressors just for 1 and 2 channel formats, and these are pervasive in PBR rendering.

**Comment by alecazam** [comment]
Here's what I did with that call.  I didn't have anywhere to stuff the control flag, so I broke the multithreading support in my encoder, but now I get more of the blocks I expect.  For L and LA, I see L and L/LA blocks.

```
else
	{
		for (int i = 0; i < 21; i++)
		{
			best_error[i][3] = 1e30f;
			best_error[i][2] = 1e30f;
			best_error[i][1] = 1e30f;
			best_error[i][0] = 1e30f;

			format_of_choice[i][3] = FMT_RGBA;
			format_of_choice[i][2] = FMT_RGB;
			format_of_choice[i][1] = FMT_LUMINANCE_ALPHA;
			format_of_choice[i][0] = FMT_LUMINANCE;
		}

        // Handle L1 and LA encoding separately, rgb/a modes won't be picked due to 1e30f best_error initialization
        for (int i = 4; i < 21; i++)
        {
            float base_quant_error = baseline_quant_error[i] * partition_size * 1.0f;
            float rgb_quantization_error = error_weight_rgbsum * base_quant_error;
            
            // handle L1
            float luminance_error = rgb_quantization_error + eci->alpha_drop_error + eci->luminance_error + rgb_range_error;
            best_error[i][0] = luminance_error;
            
            // handle LA or L1
            if (gAstcenc_UniqueChannelsInPartitioning >= 2)
            {
                float alpha_quantization_error = error_weight.w * base_quant_error;
                float rgba_quantization_error = rgb_quantization_error + alpha_quantization_error;

                float lum_alpha_error = rgba_quantization_error + eci->luminance_error + rgb_range_error + alpha_range_error;

                best_error[i][1] = lum_alpha_error;
                //format_of_choice[i][1] = FMT_LUMINANCE_ALPHA;
            }
        }
        
        // handle RGB/A or LA or L1
        if (gAstcenc_UniqueChannelsInPartitioning >= 3)
		// pick among the available LDR endpoint modes
		for (int i = 4; i < 21; i++)
		{
			float base_quant_error = baseline_quant_error[i] * partition_size * 1.0f;
			float rgb_quantization_error = error_weight_rgbsum * base_quant_error;
			float alpha_quantization_error = error_weight.w * base_quant_error;
			float rgba_quantization_error = rgb_quantization_error + alpha_quantization_error;

			// for 8 integers, the available encodings are:
			// full LDR RGB-Alpha
			float full_ldr_rgba_error = rgba_quantization_error;

			if (eci->can_blue_contract)
			{
				full_ldr_rgba_error *= 0.625f;
			}

			if (eci->can_offset_encode && i <= 18)
			{
				full_ldr_rgba_error *= 0.5f;
			}

			full_ldr_rgba_error += rgb_range_error + alpha_range_error;

			best_error[i][3] = full_ldr_rgba_error;
			//format_of_choice[i][3] = FMT_RGBA;

            //-----------------------------------
			// for 6 integers, we have:
			// - an LDR-RGB encoding
			// - an RGBS + Alpha encoding (LDR)

			float full_ldr_rgb_error = rgb_quantization_error;

			if (eci->can_blue_contract)
			{
				full_ldr_rgb_error *= 0.5f;
			}

			if (eci->can_offset_encode && i <= 18)
			{
				full_ldr_rgb_error *= 0.25f;
			}

			full_ldr_rgb_error += eci->alpha_drop_error + rgb_range_error;

			float rgbs_alpha_error = rgba_quantization_error + eci->rgb_scale_error + rgb_range_error + alpha_range_error;

			if (rgbs_alpha_error < full_ldr_rgb_error)
			{
				best_error[i][2] = rgbs_alpha_error;
				format_of_choice[i][2] = FMT_RGB_SCALE_ALPHA;
			}
			else
			{
				best_error[i][2] = full_ldr_rgb_error;
				//format_of_choice[i][2] = FMT_RGB;
			}

            //-----------------------------------
            // for 4 integers, we have a Luminance-Alpha encoding and the RGBS encoding
			float ldr_rgbs_error = rgb_quantization_error + eci->alpha_drop_error + eci->rgb_scale_error + rgb_range_error;

            float lum_alpha_error = best_error[i][1]; // rgba_quantization_error + eci->luminance_error + rgb_range_error + alpha_range_error;

			if (ldr_rgbs_error < lum_alpha_error)
			{
				best_error[i][1] = ldr_rgbs_error;
				format_of_choice[i][1] = FMT_RGB_SCALE;
			}
		}
	}
```

**Comment by solidpixel** [comment]
> I thought dual-plane was a decision across the entire image,

The only decisions per image are block size, and linear vs sRGB. Everything else is chosen per block. 

> That would cut the endpoint storage down to 1 or 2 bytes per endpoint, and then more data for quality would be dedicated to partitioning schemes. 

Note "dual plane" and "two component endpoint" are different things. In ASTC terminology, dual plane = storing two weights per texel. Any color endpoint can use dual plane, but it does chew through a lot of bits. 

> It does seem a lot like a mask to say, incoming data is known to be L or LA, so mask out the work done for rgb/a. ETC and BC all have dedicated compressors just for 1 and 2 channel formats, and these are pervasive in PBR rendering.

Yes, I agree we could do more to specialize on known properties of the image. The way the encoder is written doesn't make that easy at the moment (short of adding an entire parallel compression path for it). I suspect it's worth doing - there are a lot of normal maps out there - but I've just not had time to look at it yet.

**Comment by solidpixel** [comment]
Removing the 2.1 milestone, given that this is shown to be working as expected.

**Comment by solidpixel** [comment]
Investigating this one more, and I'm not getting any appreciable speedup by forcing L+A endpoint searches to only use two planes. I'm not too surprised - the final endpoint selection doesn't show as particularly significant in the profiles - but figured it was worth checking. 

Rejecting, as I don't see this as worth the additional complexity.
