### ISSUE TITLE
Is possible support premultiplyAlpha?

### ISSUE THREAD

**Issue by halx99** [ARM-software/astc-encoder#175]
RT

**Comment by solidpixel** [comment]
Yes, we can add support for this. 

It makes a lot of sense to do this in the compressor, as we can doing the multiplication in float domain and maintain more precision than quantizing ahead of time and quantizing back to 8 bits. 

Initially we'd probably only support this for LDR and sRGB textures (where premultiplication is applied to a linearized RGB value, before being re-gamma encoded).

**Comment by halx99** [comment]
Thanks for yor reply, looking forward for this feature

**Comment by solidpixel** [comment]
Preview available on PR #183.

**Comment by solidpixel** [comment]
PR merged. Closing.

**Comment by halx99** [comment]
Excellent
