### ISSUE TITLE
Support for mipmapping?

### ISSUE THREAD

**Issue by TimvanScherpenzeel** [ARM-software/astc-encoder#20]
Hi,

Recently I've been working on creating an open source CLI tool for texture compressing in all common formats (ASTC, ETC, PVR and S3TC) for WebGL. I've looked in the source code but I haven't been able to find an option to generate mipmaps with Astcenc. Is there a way to pass a flag to enable mipmapping and if not, is this something on the roadmap? I have noticed that PVRTexTool is able to generate mipmaps but unfortunately I don't think I have access to the source code.

If you are interested, the compression tool can be found here: https://github.com/TimvanScherpenzeel/texture-compressor/blob/master/lib/compressWithASTC.js

Many thanks in advance,

Tim

**Comment by solidpixel** [comment]
The compressor compresses single input images to a single output image; with the current codebase if you want to create mipmaps you'll need to downsample them in an external tool, compress them individually, and then package up in an wrapper format.

Cheers, 
Pete

**Comment by TimvanScherpenzeel** [comment]
Hi Pete,

Thanks for your response and the clarification 👍
