### ISSUE TITLE
Support a basic RDO preprocess for transparency in sprite sheets

### ISSUE THREAD

**Issue by solidpixel** [ARM-software/astc-encoder#208]
One common use case for mobile games is 2D sprite rendering, and many sprite atlases consist of a significant amount of transparent texels. If the atlas is using extruded RGB to preserve edges across filtering it is likely that the transparent blocks will all contain different data, even if `-a` is used to suppress the error on the RGB channels, which limits the impact of any additional application compression applied (e.g. reducing the benefit of `zip` for Android APKs). 

For this specific use case we can perform a simple transform to replace transparent blocks that are disconnected from non-transparent blocks (i.e. so color channels will never get picked for filtering) with a known constant color block. This should have no impact on the data, and will improve the packaging compressibility of the data.

**Comment by andrewevstyukhin** [comment]
For really invisible texels that are far from other non-zero alpha texels, I assume zero RGB weight in the error metric.
The mask can be computed from the source alpha and a distance specified in the command-line.

When a simple constant color fill can be detrimental to the edges, unspecified RGB can even help to focus attention on visible texels.

Yes, completely invisible blocks can be compressed very quickly with the already known answer.

**Comment by solidpixel** [comment]
Just as a test I tried out a basic offline pre-process which turns entirely transparent blocks into constant color blocks if all neighboring blocks (including diagonals) are entirely transparent. 

If we ignore alpha it looks something like this:

![EtK3ZpPW8AEYmgC](https://user-images.githubusercontent.com/23016617/106572398-45464200-6530-11eb-9a15-c968c4ba485b.jpg)

Testing with `zip` on Linux (default settings), compression ratio increases by 5% (17% compression ratio with extruded edges everywhere, 23% with constant color blocks).

Leaving an entire block of buffer is a safe, but conservative, configuration. The maximum distance to a non-transparent edge is `2 * block_dim - 1`, which could probably be reduced to 2 or 3 pixels.

**Comment by solidpixel** [comment]
In terms of a real implementation design for this, we could do this using the existing `-a <radius>` setting that exists for scaling channel error weight by the alpha value. We already have the summed-area-table for each block based on the alpha radius, so we can use this to determine the safety condition.

**Comment by andrewevstyukhin** [comment]
I also use a special extrusion algorithm based on weights:
	static const int delta_y[12] = { -1, 0, 0, 1, -1, -1, 1, 1, -2, 0, 0, 2 };
	static const int delta_x[12] = { 0, -1, 1, 0, -1, 1, -1, 1, 0, -2, 2, 0 };
	static const int delta_w[12] = { 10, 10, 10, 10, 7, 7, 7, 7, 5, 5, 5, 5 };
If I can get test image somewhere you'll can compare sizes with an alternative extrusion...

**Comment by solidpixel** [comment]
Original image (pre extrusion)

![sprite2](https://user-images.githubusercontent.com/23016617/106575130-a02d6880-6533-11eb-9fe2-7a691f5a81dc.png)

For a first implementation I would expect edge extrude to be handled before calling `astcenc`, so all the tool would handle internally is the constant color block assignment based on the alpha value.

**Comment by andrewevstyukhin** [comment]
Looks like this image was restored from PMA becase it has a noise near edges...
![badly](https://user-images.githubusercontent.com/7923719/106576296-07f0ad00-654e-11eb-97b3-156706374ba6.png)

**Comment by andrewevstyukhin** [comment]
![arm1](https://user-images.githubusercontent.com/7923719/106576719-877e7c00-654e-11eb-9194-0c90ca590c47.png)

**Comment by solidpixel** [comment]
> Looks like this image was restored from PMA because it has a noise near edges...

Yes, the original isn't great.

**Comment by solidpixel** [comment]
Prototype based on the `-a <radius>` setting: 

* https://github.com/ARM-software/astc-encoder/tree/zardo

Compression sizes based on your extrude:

```
bzip2 -9v sprite_ext_orig.astc
sprite_ext_orig.astc:  1.095:1,  7.305 bits/byte,  8.69% saved, 700432 in, 639589 out.

bzip2 -9v sprite_ext_rdo.astc
sprite_ext_rdo.astc:  1.382:1,  5.791 bits/byte, 27.62% saved, 700432 in, 506987 out.
```

Useful command lines:

```
// Compress with a safety radius of 2
./astcenc-avx2 -cl sprite.png sprite.astc 4x4 -thorough -a 2

// Decompress, dropping alpha for visualization
./astcenc-avx2 -dl sprite.astc sprite_out.png -dsw rgb1
```

**Comment by andrewevstyukhin** [comment]
Summary:
- 17% compression ratio with extruded edges
- 23% with constant color blocks
- 27.62% saved, thanks to precise radius (and maybe? Gaussian blur).

I like these results! -10% is awesome

**Comment by solidpixel** [comment]
Let me kick some tires with a few other users I know are using the `-a` setting. I just want to check they are happy with changing the default behavior, or whether we need a new flag to enable this.

**Comment by solidpixel** [comment]
I general adding an `-rdo` setting might be a future-proof opt-in for more invasive forms of RDO that start to trade quality for bitrate.

**Comment by andrewevstyukhin** [comment]
I suppose backard capability

**Comment by solidpixel** [comment]
> I like these results! -10% is awesome

On a sample of one texture, for your extrude algorithm the post-compression saving is closer to 20% (your extrude smooths out the further from the opaque edge you get, so you get more variation in the blocks - color endpoints are different). 

> I suppose backward capability

Yes. Although in this case it shouldn't matter - if you are using the `-a` option with zero alpha texels you should have no real expectation of preserving sensible content (as the error weight for those channels will be zero).

**Comment by solidpixel** [comment]
Tuned the alpha threshold for the prototype; the check was still getting some false positives off the summed-area-tables. We know the min valid value for uses alpha is ~2.7e-5 (1 part in 255 for a single pixel a 12x12 block), so we use just below this as the threshold rather than 1e-6. 

This improves bzip compression rate by another 0.8%.

**Comment by solidpixel** [comment]
| Block Size | .astc KB | Old .astc.bz2 KB | New .astc.bz2 KB | Reduction in .bz2 size |
| --- | --- | --- |--- | --- |
| 4x4 |   684 |   602 |   482 | 19.9% |
| 5x5 |   438 |   386 |   318 | 17.5% |
| 6x6 |   304 |   270 |   224 | 17.1% |
| 8x8 |   172 |   144 |   125 | 13.2% |

**Comment by solidpixel** [comment]
Merged - on by default if you use the `-a` option.
