### ISSUE TITLE
Blank image/artefacts when converting from EXR to ASTC

### ISSUE THREAD

**Issue by chris-unity** [ARM-software/astc-encoder#211]
Hi, I've been trying to use astcenc-sse2 to convert a [sample EXR](https://filesamples.com/samples/image/exr/sample_640%C3%97426.exr) into the ASTC format. As it is an EXR file I would expect to use the _-cH_ parameter to do this, but the resulting image is pure white. This is the command I'm using:

`astcenc-sse2 -cH sample.exr sample.astc 6x6 -medium`

Using _-cl_ results in a recognisable image, albeit with heavy artefacting. I've have tried this with an EXR saved out from Photoshop (both with Wavelet compression and no compression) which result in the same effects.

I've found this issue occurs in the 2.3 and 2.0 builds of astcenc-sse2. Is this an expected use case?

**Comment by solidpixel** [comment]
Yes, this "should work" - sounds like we have a bug somewhere.

**Comment by solidpixel** [comment]
Looks to be an issue with HDR images getting skewed if the image isn't a multiple of block height.

**Comment by solidpixel** [comment]
Bug was a transposed row/col pixel offset when loading HDR images, so non-square HDR images would pick up an image skew as the image load progressed. Could result in an out-of-bounds access, so will queue up a patch release.

@chris-unity let me know if this solves the issue (GitHub closed the issue automatically).

**Comment by solidpixel** [comment]
Release 2.4 published, which pulls in this as a fix.

**Comment by chris-unity** [comment]
Thanks @solidpixel , this fixes the issue when using the _-cl_ parameter. Using _-ch_ or _-cH_ however still results in a blank white image. Is this expected?

**Comment by solidpixel** [comment]
Not expected - it seemed to work for me here. 

* What OS are you running on?
* Did you build your own binaries?
    * If yes, what cmake configure line?
    * ... and which compiler/version?

**Comment by solidpixel** [comment]
```
./astcenc/astcenc-sse2 -cH sample.exr sample.astc 6x6 -medium
./astcenc/astcenc-sse2 -dH sample.astc sample-out.exr
```
Output (screenshotted from GIMP) is:

<img width="343" alt="screengrab" src="https://user-images.githubusercontent.com/23016617/107622676-1591eb00-6c50-11eb-8e1e-2a1df824f6e6.png">

**Comment by chris-unity** [comment]
Thanks @solidpixel , I think this is just my misunderstanding that the HDR encoded `sample.astc` cannot be displayed by the Mac Preview viewer. Converting it back to an `exr` works perfectly so the information is all there :)
