### ISSUE TITLE
Compilation isssue: _mm_popcnt_u64 is not support in SSE 4.1 compiling using g++ 4.8.5

### ISSUE THREAD

**Issue by rchardx** [ARM-software/astc-encoder#241]
Environment: RedHat Linux x86_64
Compiler: g++ 4.8.5

Currently, astic-encoder uses SSE 4.1 by default.
However, _mm_popcnt_u64 in <immintrin.h> was introduced in Intel SSE 4.2 (see the macros in <smmintrin.h>).

Should astc-encoder use SSE 4.2 instead?

Best wishes

**Comment by rchardx** [comment]
In addition, __get_cpuid_count is not supported in g++ 4.8.5 as well.

**Comment by solidpixel** [comment]
The 4.8 compiler series is ancient (4.8.0 was 2013), so TBH the best solution is just to update to a newer compiler. We officially support g++ 7.5 or newer. I'd recommend using clang++ 9 or newer - it tends to out-perform g++ by ~15%.

> However, _mm_popcnt_u64 in <immintrin.h> was introduced in Intel SSE 4.2 (see the macros in <smmintrin.h>).

The popcnt instruction isn't strictly part of SSE 4.2. It has a separate feature bit and is widely available on older AMD processors that support SSE 4a but not 4.2.

**Comment by solidpixel** [comment]
Note, if you need to edit the build, use of POPCNT is a separate enable to the SSE enable, so you can just tweak the define to enable/disable.

**Comment by solidpixel** [comment]
Closing; newer compiler recommended.
