### ISSUE TITLE
Some changes for v2.5 to fix compile and link issues.

### ISSUE THREAD

**Issue by alecazam** [ARM-software/astc-encoder#243]
I'm getting a link error on cpu_supports_popcnt(), so I think this #if check needs to move after the include.  Then the defines are setup properly, since these should be a global define in my case.   Sorry these aren't a PR, but I'm a bit swamped right now.  

```
#include "astcenc_internal.h"

#if (ASTCENC_SSE > 0)    || (ASTCENC_AVX > 0) || \.   <- moved below include
    (ASTCENC_POPCNT > 0) || (ASTCENC_F16C > 0)
```

Also moved this to the top of astcenc_mathlib.h, so that Intel x64 paths are excluded.  This helps with people transitioning from the old headers who might have set these in their CMakeLists.txt files.  Very nice that now all these flags are setup from the compile configuration.  That makes building universal binariess on macOS a lot easier now, and the CMake scripts easier.  Great work!

```
...
#include <cstdint>
#include <cmath>

#ifndef ASTCENC_NEON
  #if defined(__aarch64__) || defined(__arm__)
    #define ASTCENC_NEON 1

    // these aren't valid on Neon
    #define ASTCENC_AVX 0   <- added
    #define ASTCENC_SSE 0   <- added
  #else
    #define ASTCENC_NEON 0
  #endif
#endif

```

**Comment by alecazam** [comment]
Also wanted to share my old and new timings building all the ASTC iOS textures on a shipping title.  This was with AVX on a 16" 8 core/16 HT MBP.  I only have AVX set, and not AVX2.   Way to go!  

Old Time: 90s (v2.2 I think)
New Time: 60s (v2.5)

**Comment by solidpixel** [comment]
Thanks for the build fixes - will get those committed and back-ported to the 2.x branch.

On my 6 core / 6 thread box AVX2 buys ~10% over SSE4.1 (pretty consistent over search quality), so it's not a huge uplift. I know performance doesn't scale linearly even to 6 threads, so with 16 (and HT) I suspect you are just seeing memory contention effects start to eat into the gains.

**Comment by solidpixel** [comment]
The #include change is now merged to main and 2.x branches. 

I don't quite get why this one is needed:

```
    // these aren't valid on Neon
    #define ASTCENC_AVX 0   <- added
    #define ASTCENC_SSE 0   <- added
```
 
... can you explain a bit more? 

If you are using compiler auto-setup and not defining these in the build system, the default paths in the blocks above should already be setting these to zero. e.g. 

```
#ifndef ASTCENC_AVX
  #if defined(__AVX2__)
    #define ASTCENC_AVX 2
  #elif defined(__AVX__)
    #define ASTCENC_AVX 1
  #else
    #define ASTCENC_AVX 0
  #endif
#endif
```
... would only be non-zero if `__AVX2__` or `__AVX__` are defined, and if that's the case, building for NEON in the same build doesn't make any sense.

**Comment by alecazam** [comment]
Yes, you can leave that one out, but I just liked the exclusivity of if one area is set, the other can't be activated.  These headers seem to be setup to allow the caller to set them from a define, and if that's set there then code breaks.    If it's not set, then you are right that the auto-detect sets those properly.

**Comment by solidpixel** [comment]
Thanks for confirming, closing as the bug is fixed.
