### ISSUE TITLE
Compression fails for 16bit-png file

### ISSUE THREAD

**Issue by NumaNumaNuma** [ARM-software/astc-encoder#25]
Hi, 

Is astcenc able to convert 16bit/24bit png's ? 
It gives a pretty clear error message when trying ("8 bit only.") but I was wondering if that was a core limitation of the algorithm or if there were ways around that.

Thanks

**Comment by solidpixel** [comment]
The core compression algorithm is agnostic of color format, and can compress LDR and HDR images. I can't see why compressing 16-bit PNGs would be a problem, although as you noted today the loader doesn't support it (we use stb_image to provide image loading, and it only supports 8-bit color depth).

**Comment by solidpixel** [comment]
Closing - original question answered.
