### ISSUE TITLE
Make the repo REUSE compliant

### ISSUE THREAD

**Issue by wasimabbas-arm** [ARM-software/astc-encoder#256]
Khronos is adopting REUSE. REUSE (https://reuse.software/) is a standardized method of declaring copyright and licensing. To use astcenc in any khronos repo including https://github.com/KhronosGroup/KTX-Software/ one has to add exceptions like [this](https://github.com/KhronosGroup/KTX-Software/commit/d5ae1ec0003e68a297e927ab32ab0096eb3ad3ba) to be able to pass CI.

**Comment by solidpixel** [comment]
Suspect following this is going to need some Arm legal approvals - the propose modifications in the Reuse FAQ will result in us deviating from the approved Arm copyright header.

**Comment by solidpixel** [comment]
Rejecting
