### ISSUE TITLE
Research better heuristics for 2 plane searches

### ISSUE THREAD

**Issue by solidpixel** [ARM-software/astc-encoder#261]
The latest `main` post-3.0 only uses 2 weight planes if a block trial has a single partition, but even that is relatively expensive to search. 

For Kodak on `-medium` removing 2 weight planes only costs a maximum of 0.05 dB PSNR loss for 6x6 blocks, and improves compression performance by 20-40%. We're spending a _lot_ of time searching state space that doesn't give much benefit. Note it _does_ help some images - 4x4 blocks, non-photographic imagery, and HDR blocks take a larger hit - so direct removal isn't an option. 

The current heuristic is a very simple metric that finds the least correlated component and then tests that against a quality-level determined threshold for whether using two planes is a good idea. However across a corpus of content we can see that metric is actually a poor predictor for whether two planes is worth trying. The image below shows the percentile distribution for the lowest correlation when using one or two planes a normal map (where we override the metric, because it is such a bad predictor):

![PercentileCorrelation](https://user-images.githubusercontent.com/23016617/121529646-85449680-c9f4-11eb-9ba2-afc0605e4845.png)

There is almost no difference between the two lines. Yes, there is a slight bias that blocks with high correlation won't benefit - but blocks using two planes with correlation factors above 0.5 are common - and most 1 plane blocks have a correlation in the "hot range" for two planes so it's a poor heuristic for culling the search space as most blocks are under the correlation threshold.

**Comment by alecazam** [comment]
Would this affect normals if removed?  Is the dual-plane block mode of ASTC?

**Comment by solidpixel** [comment]
Yes, removing completely is a large quality hit for normals. The main trick is trying to find an accurate anti-predictor to prune the search tree and remove cases where it is very unlikely to help.

**Comment by solidpixel** [comment]
Evidence-based anti-predictor committed (try one two plane search, and if that makes things a lot worse than the best one plane, then skip the rest). This has solved the worst of the "bad search" problem.
