### ISSUE TITLE
ASTC encoder doesn't favor transparent pixels

### ISSUE THREAD

**Issue by alecazam** [ARM-software/astc-encoder#262]
I have a non-zero mode to my debug visualization.  What I'm noticing is that bc7enc generates a lot more transparent pixels that line up with the original content, and astc-encoder generates blocky pixels without any transparency.  Both formats have partitioning too.  

I'm running default quality so -medium level from my encoder kram.  And it's using astc-encoder v2.5.

These are low value alpha like 0 to 3/255, but they're the edges of a particle atlas.  Will try to upload a png example when I have time.  

Same block from astc-encoder.  This is an astc 4x4 image
![image](https://user-images.githubusercontent.com/3750359/121732739-6f43de00-caa7-11eb-82c3-b8931c198914.png)

A particle shape in non-zero alpha debug mode in astc-encoder.
![image](https://user-images.githubusercontent.com/3750359/121732999-c3e75900-caa7-11eb-9267-543e5c588be5.png)

Note the nicer outline where astc-encoder is blocky above

bc7enc - bc7 but not all modes are implemented
![image](https://user-images.githubusercontent.com/3750359/121732663-5dfad180-caa7-11eb-912f-0b70684e983e.png)

bc7enc and that same shape.
![image](https://user-images.githubusercontent.com/3750359/121733107-e8dbcc00-caa7-11eb-9bd7-3980817ba7f4.png)

**Comment by solidpixel** [comment]
Thanks, will take a look.

**Comment by solidpixel** [comment]
Some starting questions:

* Are you compressing a sprite with extruded color channels to avoid edge fringing?
* Are you using the `-a` option?

By default the compressor assumes all 4 channels are equally weighted, e.g. like material data, so if you have extruded color in low-transparency blocks the compressor tries to keep all 4 channels accurate which is a challenge (as extruded edges often have complex high frequency patterns to compress).

If you know that the alpha channel is actually alpha try using the `-a` option to the compressor - this scales the error weight of the RGB channels by the transparency - so "encourages" the compressor to preserve alpha more accurately.

**Comment by solidpixel** [comment]
Here is an example compressed with no additional settings:

![Normal](https://user-images.githubusercontent.com/23016617/121752198-8a463a80-cb07-11eb-9a02-d31fe9594c3d.png)

... and the same example compressed with `-a 1` on the command line (flag `ASTCENC_FLG_USE_ALPHA_WEIGHT` set and `a_scale_radius = 1` in the config for the API).

![Transparency](https://user-images.githubusercontent.com/23016617/121752204-8d412b00-cb07-11eb-8717-46e63757a410.png)

**Comment by alecazam** [comment]
In this case, it's from a particle atlas that is alpha only.  I would think when the block is all 000's in rgb, and just an alpha channel that even with equal weighting, the compression emphasis would be on preserving the alpha channel that has data.  In this case the alpha value are tiny though on the fringes of the particles.    

I'll check my settings more closely in kram, and see if tweaking the settings help.  I think I do equal weights on the channels, but could zero out the rgb.  The problem is this atlas has some blue channel on a few of the particles that is specific to one shader so I can't globally assume alpha-only.

**Comment by solidpixel** [comment]
Hmm, if rgb is zero I'd expect it to try harder. Can you share a repro? Email developer at arm dot com if you can't share publicly.

**Comment by solidpixel** [comment]
In terms of encoding, remember that a texture that is effectively `00BA` doesn't fit an astcenc endpoint encoding so you're going to end up storing 4 component RGBA endpoints in that case. Swizzling to BBBA before encoding might help if you can.

**Comment by solidpixel** [comment]
@alecazam I'm closing this one, as there doesn't seem to be an issue here (using the `-a` setting is the expected usage if you want to alpha-weight color error). Feel free to re-open with a repro if there is an issue that still needs investigating. 

Cheers,
