### ISSUE TITLE
Simplify CMake configure and support universal binaries

### ISSUE THREAD

**Issue by solidpixel** [ARM-software/astc-encoder#268]
We want to be able to build universal binaries for macOS (and likely Windows in future), while retaining the ability to build multiple single SIMD variants. This requires some level of multi-arch support in the build system, which it currently cannot handle 

## Remove ARCH

The first task is to remove the `-DARCH` option from the CMake files, keeping the existing single architecture build behavior. It's only really used to validate the `-DISA_*` settings, so we can just remove it and infer what we need from the ISA setting. Architecture agnostic ISA variants (`ISA_NONE`, `ISA_NATIVE`) don't set architecture specific options, so will pick up whatever default compiler architecture is specified and use that. 

We should detect conflicting ISA settings that imply multiple architectures (e.g. both SSE and NEON set) and throw a clean error. 

 Will also need to update the Jenkinsfiles and Build docs.

Note that `-DARCH` is used in the packaging step - so we will probably need keep the ARCH option just to name an unambiguous bundle name. However, it should be optional and "normal users" won't need to use it. We can't use the ISA variant in all cases, as NONE and NATIVE are indeterminate, so the manual control is useful. 

## Allow user CMAKE_OSX_ARCHITECTURES

For macOS universal builds there are two possible routes, and we probably want to support both for sake of consistency.  

The first option (which is most compatible with our build options from other platforms) is to allow the user to specify both `ISA_<x64>=ON` and `ISA_NEON=ON` on a single configure line. This should be converted internally into `CMAKE_OSX_ARCHITECTURES=x86_64;arm64`. To be clear about what has been built, the name of this binary should be e.g. `astcenc-sse2-neon`. 

The second option (which is most compatible with using XCode to build) is to specify `-DCMAKE_OSX_ARCHITECTURES=x86_64;arm64` on the configure line and then autoselect the ISA variant options to use. The safe default for this is to select SSE2 for x64 and NEON for aarch64, as this is only guaranteed level of support in these architectures, but we should allow the user to also specify an enhanced ISA for x64 if they want one.

Note for single architecture builds on macOS it must still be possible to build all of the valid variants for that architecture in a single configure.

**Comment by abbaswasim** [comment]
> Note that -DARCH is used in the packaging step - so we will probably need keep the ARCH option just to name an unambiguous bundle name

Not sure what you mean by the unambiguous name. Arch wasn't used in the binary names anywhere. Only reference to this is in Jenkins like 
```
            stage('Build R') {
              steps {
                sh '''
                  mkdir build_rel
                  cd build_rel
                  cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../ -DISA_NEON=ON -DARCH=aarch64 ..
                  make install package -j1
                '''
              }
```

I would like to go with second option for `CMAKE_OSX_ARCHITECTURES`

**Comment by solidpixel** [comment]
> Not sure what you mean by the unambiguous name. Arch wasn't used in the binary names anywhere.

It's used in the CPack bundle name:

`set(CPACK_PACKAGE_FILE_NAME "astcenc-${PKG_VER}-${PKG_OS}-${ARCH}")`

> I would like to go with second option for `CMAKE_OSX_ARCHITECTURES`

I was really thinking we should try to support both (as the CMAKE_OSX...) line is fine for XCode, but typing it by hand is a real pain ...

**Comment by abbaswasim** [comment]
> set(CPACK_PACKAGE_FILE_NAME "astcenc-${PKG_VER}-${PKG_OS}-${ARCH}")

**Comment by wasimabbas-arm** [comment]
What are the implications of this on cross compilation? Do you know?

**Comment by solidpixel** [comment]
> Just the fact that two conflicting/different architecture ISAs are specified on command line?

Yes, that was my thinking. Either because CMAKE_OSX_ARCHITECTURES contains two architectures, or because it's not set and two conflicting ISA_ARCH options are set. Only for macOS, of course, anything else should fail with a nice error.

**Comment by wasimabbas-arm** [comment]
This is problematic because if someone want's to build `x86;x86_64` they will not have `-DISA_NEON` so very hard to guess what's conflicting ISA.

**Comment by wasimabbas-arm** [comment]
Further not sure how to differentiate between conflicting ISA i.e. no NEON supplied vs NON-Universal build required for something like `cmake -H. -Bbuild -DISA_AVX2=ON -DISA_SSE2=ON ..` If we say if more than one x86 ISA is specified and no NEON then build non-universal binary otherwise build universal and verify that then `cmake -H. -Bbuild -DISA_AVX2=ON ..` doesn't work.

**Comment by wasimabbas-arm** [comment]
In conclusion I think its better to go with option two. Be more explicit, follow cmake documentation and have a simpler implementation.

**Comment by solidpixel** [comment]
> This is problematic because if someone want's to build x86;x86_64 

Why would you want to? Catalina dropped support for 32-bit apps, and macOS has supported 64-bit for years. There is literally no need to ever build 32-bit apps for macOS.

**Comment by wasimabbas-arm** [comment]
First implementation with the assumption that more than one x64 ISA means non-universal build. https://github.com/ARM-software/astc-encoder/pull/266/commits/bd45b6fbeec399537d1fa1cf5c7dd762f455791d

**Comment by wasimabbas-arm** [comment]
I think this implementation works. Following are the tests I have performed with a message like:
`message("Build continue: UNIVERSAL_BUILD=${UNIVERSAL_BUILD},CMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES},ARCH_STRING=${ARCH_STRING},ISA_NONE=${ISA_NONE},ISA_NATIVE=${ISA_NATIVE},ISA_AVX2=${ISA_AVX2},ISA_SSE41=${ISA_SSE41},ISA_SSE2=${ISA_SSE2}")
`

```
 $ cmake -H. -Bbuild -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
-- Building universal binary for arm64;x86_64
  Build continue: UNIVERSAL_BUILD=ON,CMAKE_OSX_ARCHITECTURES=arm64;x86_64,ARCH_STRING=_arm64_x86_64,ISA_NONE=OFF,ISA_NATIVE=AUTO,ISA_AVX2=OFF,ISA_SSE41=OFF,ISA_SSE2=ON

$ cmake -H. -Bbuild -DISA_SSE41=ON -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
  Incomplete ISAs specified for universal build.  Use ISA_NEON and one of
  ISA_NONE|ISA_NATIVE|ISA_AVX2|ISA_SSE41|ISA_SSE2 for universal build.

$ cmake -H. -Bbuild -DISA_SSE41=ON -DISA_NEON=ON -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
-- Building universal binary for arm64;x86_64
  Build continue: UNIVERSAL_BUILD=ON,CMAKE_OSX_ARCHITECTURES=arm64;x86_64,ARCH_STRING=_arm64_x86_64,ISA_NONE=OFF,ISA_NATIVE=AUTO,ISA_AVX2=OFF,ISA_SSE41=ON,ISA_SSE2=ON

$ cmake -H. -Bbuild -DISA_NEON=ON -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
  Incomplete ISAs specified for universal build.  Use ISA_NEON and one of
  ISA_NONE|ISA_NATIVE|ISA_AVX2|ISA_SSE41|ISA_SSE2 for universal build.

$ cmake -H. -Bbuild -DISA_SSE41=ON -DISA_NEON=ON
-- Building universal binary for arm64;x86_64
  Build continue: UNIVERSAL_BUILD=ON,CMAKE_OSX_ARCHITECTURES=arm64;x86_64,ARCH_STRING=_arm64_x86_64,ISA_NONE=OFF,ISA_NATIVE=AUTO,ISA_AVX2=OFF,ISA_SSE41=ON,ISA_SSE2=OFF

$ cmake -H. -Bbuild -DISA_NEON=ON
  Build continue: UNIVERSAL_BUILD=OFF,CMAKE_OSX_ARCHITECTURES=,ARCH_STRING=_arm64,ISA_NONE=OFF,ISA_NATIVE=AUTO,ISA_AVX2=OFF,ISA_SSE41=OFF,ISA_SSE2=OFF

$ cmake -H. -Bbuild -DISA_AVX2=ON
  Build continue: UNIVERSAL_BUILD=OFF,CMAKE_OSX_ARCHITECTURES=,ARCH_STRING=_x86_64,ISA_NONE=OFF,ISA_NATIVE=AUTO,ISA_AVX2=ON,ISA_SSE41=OFF,ISA_SSE2=OFF

$ cmake -H. -Bbuild -DISA_SSE41=ON -DISA_AVX2=ON
  Build continue: UNIVERSAL_BUILD=OFF,CMAKE_OSX_ARCHITECTURES=,ARCH_STRING=_x86_64,ISA_NONE=OFF,ISA_NATIVE=AUTO,ISA_AVX2=ON,ISA_SSE41=ON,ISA_SSE2=OFF

$ cmake -H. -Bbuild -DISA_SSE41=ON -DISA_AVX2=ON -DISA_NEON=ON
  Conflicting ISAs specified.  Only one of
  ISA_NONE|ISA_NATIVE|ISA_AVX2|ISA_SSE41|ISA_SSE2 is valid with ISA_NEON.

$ cmake -H. -Bbuild -DISA_AVX2=ON -DISA_SSE41=ON -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
 Conflicting ISAs specified for universal build.  Use ISA_NEON and one of
  ISA_NONE|ISA_NATIVE|ISA_AVX2|ISA_SSE41|ISA_SSE2 for universal build.

$ cmake -H. -Bbuild -DISA_AVX2=ON -DISA_SSE41=ON
  Build continue: UNIVERSAL_BUILD=OFF,CMAKE_OSX_ARCHITECTURES=,ARCH_STRING=_x86_64,ISA_NONE=OFF,ISA_NATIVE=AUTO,ISA_AVX2=ON,ISA_SSE41=ON,ISA_SSE2=OFF
```

**Comment by solidpixel** [comment]
PR merged.
