### ISSUE TITLE
Request for transform function of input image.

### ISSUE THREAD

**Issue by Realitian** [ARM-software/astc-encoder#275]
Hi,

I wanna ask whether does exist the functionality to transform(scale, transition, rotation) of input images.

ex:
astcenc -i input.jpg -transform (0.5, 0, 0, 0, 0.5, 0, 0, 0, 1)

please let me know if you have it already.
thank you in advance.

Cheers.

**Comment by solidpixel** [comment]
The command line tool supports image y-flip for compression and decompression which allows developers to use the same source image across APIs with different texture origins. 

There currently isn't any support for arbitrary transforms or more complex operations that are normally needed in a full asset pipeline (mipmapping, packing into ktx wrapper formats, etc). The current goal of this project is really to only provide an efficient core codec, and assumes that users who need a more complex content pipeline will likely build their own. I tend to build command line pipelines using ImageMagick if I need anything more complex.

**Comment by Realitian** [comment]
thx, but it was another recommended option.
