### ISSUE TITLE
Some image compressed with '-cs -pp-premultiply' incorrect, '-cl -pp-premultiply' correct

### ISSUE THREAD

**Issue by halx99** [ARM-software/astc-encoder#279]

**Comment by solidpixel** [comment]
The current code assumes data is in linear format. For sRGB we need a three step sequence:

- Linearize
- Premultiply
- Delinearize

**Comment by halx99** [comment]
Thanks for your reply, so the sRGB with -pp-premultiply doesn't supported by current version of `astcenc`

**Comment by solidpixel** [comment]
Correct - currently it's broken. Will try and fix this before the end of the week.

**Comment by halx99** [comment]
Thanks, excellent, looking forward that.

**Comment by solidpixel** [comment]
Do you have a more concrete example of what's going wrong for you?  

It looks like the current code is actually applying the linearize before premultiplication, which is what I thought was missing.

**Comment by halx99** [comment]
Due to security reason, I send the example to to your email

**Comment by halx99** [comment]
May email is `halx99 at dot live`

**Comment by solidpixel** [comment]
Just to explain what is currently happening in the code ...

For ASTC only the RGB channels are gamma encoded, so the assumption is that the alpha is a linear-space alpha that needs to be applied to linear color-space RGB values. This matches how the alpha value would be used during blending in shader code. 

The current preprocess code will: 

* Load the sRGB value from the image
* Convert the RGB components to linear color
* Apply the premultiply to the linear colors (rgb * a)
* Convert the premultiplied linear RGB colors back to sRGB
* Store this back to a temporary float surface to avoid losing precision
* Use the temporary float surface during compression

**Comment by solidpixel** [comment]
Quick and dirty example (might be rounding on the numbers due to compression):

```
sRGB:   0.251 0.753 0.000 0.867
Linear: 0.051 0.527 0.000 0.867
Premul: 0.044 0.457 0.000 0.867
Premul+sRGB:   0.231 0.706 0.000 0.867
```

This final value is what ends up getting compressed.

**Comment by solidpixel** [comment]
Discussed offline - issue caused by a linear-vs-sRGB mismatch, so there is no issue in the compressor.

Closing.
