### ISSUE TITLE
Is there a way to tell if an astc file was encoded with hdr profile? 

### ISSUE THREAD

**Issue by yanivams** [ARM-software/astc-encoder#280]

**Comment by solidpixel** [comment]
From the raw data, the only way to know is to decompress every block and check if it's using an HDR encoding. 

For most real implementations the content creator knows and already has to pass along metadata about the texture data (resolution, color profile, block size), so it's normally easier just to add this info into the metadata block that gets passed around with the raw data.

**Comment by yanivams** [comment]
Thanks! I wanted to ma

**Comment by yanivams** [comment]
Thanks!
