### ISSUE TITLE
Is 3.1 output compatible with 1.7/2.0?

### ISSUE THREAD

**Issue by cpxnet** [ARM-software/astc-encoder#282]
Hi,
Great job, can't wait to try out 3.1!
There is one concern though.
Is exsiting hardware decoders, which are designed for 1.X or 2.0, support 3.1 without any update?

**Comment by solidpixel** [comment]
Yes - the output data format is compatible with the ASTC standard spec in all cases.

**Comment by cpxnet** [comment]
Thanks alot!
