### ISSUE TITLE
Threading bug

### ISSUE THREAD

**Issue by jbright282** [ARM-software/astc-encoder#283]
Hi -- We were having an issue of corrupted tiles in our results, and I narrowed it down to a bug in astc_context_alloc().

The context is supposed to maintain all state so you can run multiple compressors in parallel . But when a context is allocated, init_quant_mode_table() initializes a global table.  If you have a compression job running, and allocate another context, this init will stomp over the previous results (temporarily) and you can get corrupted tiles in any current running jobs.

In our local code i've made a divergence where we lock and only init this static data once.  I do appreciate the "// TODO: Currently static memory; should move to context memory" comment.  This isn't an issue for prepare_angular_tables() -- those values are only written once. So any secondary init doesn't change it.  BUt init_quant_mode_table() inits the values, and then loops through them.  I don't expect this is a viable solution for you, but FYI there is an issue here.

astc_entry.cpp - 802

	// TODO: Currently static memory; should move to context memory
        #if !defined(ASTCENC_DECOMPRESS_ONLY)
	     prepare_angular_tables();
       #endif

	//DIVERGENCE --- init_quant_mode_table() initializes some global lookup tables and is NOT THREAD SAFE.
	//comment above is true - this should be in context memory.
	//DIVERGENCE - locking so only initialized once
	static bool doInit = true;
	if (doInit)
	{
		globalMutex.lock();
		if (doInit)
			init_quant_mode_table();
		doInit = false;
		globalMutex.unlock();
	}
	//END DIVERGENCE

	return ASTCENC_SUCCESS;
}

**Comment by solidpixel** [comment]
Thanks for the bug report and the investigation - will get this one fixed asap.

**Comment by solidpixel** [comment]
* Option one: Move to context memory.
* Option two: Just make this a ROM table, it's not large.

Will try option one, and see if it has much performance impact.

**Comment by solidpixel** [comment]
Option one has ~1% performance hit, so decided to go with option two. 

https://github.com/ARM-software/astc-encoder/pull/284

**Comment by solidpixel** [comment]
Backported to 2.x in commit a93bacf
