### ISSUE TITLE
unabled to start program

### ISSUE THREAD

**Issue by M-hypnos** [ARM-software/astc-encoder#300]
i have genarate project by Cmake， but when i start program in Microsoft Visual Studio 2019，it report an error：

`Unable to start programe`
`“..\astc-encoder-main\build\x64\Debug\ALL_BUILD”.`
`Access is denied.`

**Comment by solidpixel** [comment]
Can you explain exactly what steps you have done?

The error sounds like you are trying to executed "ALL_BUILD" which is a directory

**Comment by M-hypnos** [comment]
i just genarate project by CMakeLists.txt in directory 'astc-encoder-main', and then start project with the generated astcencoder.sln flie in VS 2019. then I start project 'ALL_BUILD'
i'm not sure if i made a mistake in generating the project by Cmake

**Comment by solidpixel** [comment]
You can't "Run" `ALL_BUILD` - it's one of the CMake pseudo-projects, not a project that builds an executable. Try to execute e.g. `astcenc-sse2`, `astcenc-sse4.1`, or , `astcenc-avx2`.

In addition, note that asctenc is a command line utility - it won't do anything useful with the default Run parameters; you'll need to pass in additional command line options.

**Comment by solidpixel** [comment]
No user update; closing.
