### ISSUE TITLE
Is there any convenient approach to convert astcenc_image to QImage or QPixmap?

### ISSUE THREAD

**Issue by ylz-at** [ARM-software/astc-encoder#301]
I am working on something like ASTC viewer.

I decompressed the astc image I get from user using `astcenc_decompress_image`,
then I converted the decompressed Image to png using `stbi_write_png_to_mem` so that I can convert it to QImage using `QImage.loadFromData`.

I am thinking if I can get rid of `stbi_write_png_to_mem` by directly converting `astcenc_image` to `QImage`.

**Comment by solidpixel** [comment]
Never tried, but something like this: https://stackoverflow.com/questions/14563180/raw-data-to-qimage

**Comment by solidpixel** [comment]
Closing, as this is unrelated to astcenc.
