### ISSUE TITLE
How to premultiplity alpha when compress a png file to astc

### ISSUE THREAD

**Issue by liuliqianxiao** [ARM-software/astc-encoder#305]
In webgl 1.0 ,I use a astc compressed texture without premultiplity alpha,
and in my project, I do something like this,
`gl.pixelStorei(WebGLRenderingContext.UNPACK_PREMULTIPLY_ALPHA_WEBGL, true);`
but it doesn't work, so, the encoder has any args to control premultiplity alpha?

**Comment by solidpixel** [comment]
If you are using the command line utility, applying premultiplication is supported using the `-pp-premultiply` command line option.

If you're using the compressor codec library, there is  no support. The image must be premultiplied before passing it into the codec.
