### ISSUE TITLE
Add ASTCENC_ namespace to library CMake variables

### ISSUE THREAD

**Issue by solidpixel** [ARM-software/astc-encoder#309]
The core library uses CMake variables without any namespace prefix. We should add one, so it's less likely to collide with other projects importing the project.

**Comment by ylz-at** [comment]
Could you please support Vcpkg as well?
so `astcenc.h` can be used easily as a lib.
I opened a port issue on Vcpkg, https://github.com/microsoft/vcpkg/issues/23744 .

**Comment by solidpixel** [comment]
This is something we can look at - although I have no idea what's involved.

**Comment by solidpixel** [comment]
Rejecting - no external user has actually complained about this, so not sure there is a real problem to solve.
