### ISSUE TITLE
Bad image output in NEON builds

### ISSUE THREAD

**Issue by solidpixel** [ARM-software/astc-encoder#316]
There is a bug in the NEON builds; running on M1 the output on standard tests is definitely broken. It is up to 1dB worse IQ than x86_64 builds (should be invariant). 

* Investigate the fix. 
* Add M1 test runs on the new CI machine.

I suspect a related failure is the image failure reported by @alecazam in #315, but the images in our failures are not as obviously broken (no blocks end up totally wrong colors - it's just a general quality reduction all over the image). It might be the same failure, so I'll fix this before investigating the other issue.

**Comment by solidpixel** [comment]
Quick bisect shows that 3.4 tag is OK, so looks to be something in the recent patches.

**Comment by solidpixel** [comment]
NEON `vint4::loada()` was broken (effectively being `vint4::load1`). Unfortunately all of the `loada` unit tests were also broken (doing aligned loads, but via the unaligned load method). Both fixed in 4c3ef88bf369ff8ad089798b53c32db0036fb8bd

**Comment by alecazam** [comment]
This fixed the block tile artifacts I was seeing on M1.  Thanks for the quick weekend fix!

**Comment by solidpixel** [comment]
No worries, thanks for the bug report. I'll leave this one open - we now have some M1 hardware in our CI farm so I'll add those to our automated testing so we catch the next NEON problem earlier.

**Comment by alecazam** [comment]
Yeah M1 is great for tests my all the block compression formats since they’re all supported.  M1 w/6+2 cpu takes 7.1s for my corpus, and Intel MBP w/8 cores takes 8.4s with current v3.4.  You’d made 450 changes since my last sync, so wanted to catch up.

**Comment by alecazam** [comment]
Sadly, running on x64, I'm seeing a lot of block artifacts in gray and normal map textures.   I have alignment set to 16, but may have to hold off on using this release of kram.  Will send some sample images as I have time to isolate them.

**Comment by alecazam** [comment]
Here's one of the textures that fails when kram encodes to astc6x6 srgb.  Mip 0 and Mip 2 I think have block artifacts.  Source is 64x64px.  I don't have a normal map yet.

![BadTextureAtsc6x6](https://user-images.githubusercontent.com/3750359/158272292-4d030eb0-a20d-478a-a793-bf4ba4b82ed9.png)

**Comment by solidpixel** [comment]
Can you create a new issue for this one please, just to keep the issue tracker history clear.

Will need a few more repro steps - tried to make a simple downsampled version of your source texture with a mipchain down to 8x8, and get no block artefacts even on `-fast`.

**Comment by alecazam** [comment]
Will do.  This was astc6x6 (not sure if by up to 8x8, you meant that you'd also tried 6x6).  I need to look at the artifacts across all the textures.

**Comment by solidpixel** [comment]
Sorry - ambiguity - I tried 6x6 blocks, with the mipchain scaled down to 8x8 (64x64, 32x32, 16x16, 8x8). Couldn't reproduce color bleed on any of them.

**Comment by solidpixel** [comment]
OK - found why I couldn't reproduce - should be fixed now.

**Comment by alecazam** [comment]
Looks good on all my maps - including normals and mips.   Thanks for all the attention on the encoder quality.   Nice speedups too.

**Comment by alecazam** [comment]
The block artifacts are mostly gone.   I have a few textures with say - white solid circle surrounded by deep blue glow, and the glow is quite blocky at 6x6.   But I'll give you a pass on that for now.  For the most part this looks a lot closer to what I got from v2.5.  Nice job!

**Comment by alecazam** [comment]
I created a test case for this at https://github.com/alecazam/kram/blob/main/tests/src/CircleGlow-d.png, but it looks fine when I use the 6x6 encoder now.  It may be an issue with the other source files alpha channels being low res.  They might have been jpg converted to png.

**Comment by solidpixel** [comment]
In terms of quality vs 2.5, I only expect two significant changes:

Transparent textures that are using the "-a" option to bias error in transparent regions in favour of alpha (i.e. error in RGB gets scaled down due to the alpha level in use). With the removal of per-texel weights we've lost the ability to do that biasing (I have some ideas to re-add a version based on block-level max alpha, but I've not done that yet, and it won't be quite as good).

Luminance textures used to get a partition count boost, +1 above the max partition count in the compressor config, but no longer do. Users can apply that bias themselves if they know the input is a luminance texture. 

The rest should mostly just be float rounding noise changes. 

In general when I'm choosing optimizations I try to keep things similar in terms of IQ, but "pareto frontier rules" apply. Small quality losses are acceptable if the "quality per performance" improves - i.e. because the compressor is faster users can always choose a more thorough search to improve image quality within the original unoptimized time budget.
