### ISSUE TITLE
Can we use this encoder on moblie platform(Android&iOS)?

### ISSUE THREAD

**Issue by Dave1991** [ARM-software/astc-encoder#319]
Currently, both the mobile platforms can not encoder the astc compressed texture in runtime exactly. Therefore, we hope to integrate this encoder by source code to the mobile platform. Then we suppose to use objective-c or jni code to call this encoder in runtime. We wonder whether our solution is feasible.

**Comment by Dave1991** [comment]
Either, is there a way to build this encoder as a library(.a, .so or .framework) for mobile platforms?

**Comment by solidpixel** [comment]
In terms of "will it function" - yes. For Arm 64-bit builds the library provides NEON acceleration, which covers most devices. We don't provide any SIMD support for 32-bit builds, although there is a fallback "no SIMD" version which will run OK (but slowly). 

For runtime usage, the main need is finding the right balance of performance and image quality. Compared to frame rendering time texture compression is slow, so you may need to use a relatively low quality search to hit the performance you need.

> Either, is there a way to build this encoder as a library(.a, .so or .framework) for mobile platforms?

The current build system uses CMake and can build a static library e.g. (https://github.com/ARM-software/astc-encoder/blob/a06b905c08e2fc2323beccf3c35fbc7e646cf615/Source/cmake_core.cmake#L29). If you need anything else you'll need to roll your own.

**Comment by Dave1991** [comment]
> Thank you! I have found the static library product in the build/Source directory. But it would be better if you could show me which header files are necessary. Then the static library will be easily integrated into mobile platforms.
> 
> > The current build system uses CMake and can build a static library e.g.
> > https://github.com/ARM-software/astc-encoder/blob/a06b905c08e2fc2323beccf3c35fbc7e646cf615/Source/cmake_core.cmake#L29

I got the answer in Utils/Example/astc_api_example.cpp. What I need is only one header file, astcenc.h. Is that right?

**Comment by solidpixel** [comment]
> What I need is only one header file, astcenc.h. Is that right?

Yes.

**Comment by Dave1991** [comment]
> For the compiler warnings, what version of C++ are you compiling with? The library interface is plain C, but the static library itself uses C++14.

I think it may be clang because I build it on Mac OS. Here is the output of `g++ --version`
`
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
`

**Comment by Dave1991** [comment]
> 

Which parts use the features of C++14? My project can only support C++11 for now.

**Comment by Dave1991** [comment]
We have built the static library for iOS(arm64) successfully. But it is really slow. It costs almost 15 seconds per image.

Whereas we have another problem, we can't open the astc file after compressing. Because we didn't pack the raw compressed data into the KTX file. But we didn't find the api for packing in the astc_api_example.cpp. Could you give us some help?

**Comment by solidpixel** [comment]
What's your image size, and what codec quality setting are you using when you create the config?

Compression is designed to be multi-threadable if that helps, but even with that for run-time usage on a mobile device you'll need to reduce the quality parameter quite a lot. Also, double check you are successfully picking up the build NEON variant (it should get selected automatically if you don't set anything, but the scalar fallback is going to be a lot slower).

In terms of format packing, the library doesn't do anything to help here - you just get the raw ASTC data. Packing into whatever container format you need is the caller's responsibility.

**Comment by Dave1991** [comment]
> What's your image size, and what codec quality setting are you using when you create the config?
> 
> Compression is designed to be multi-threadable if that helps, but even with that for run-time usage on a mobile device you'll need to reduce the quality parameter quite a lot. Even so, compression is slow (the `-fastest` mode on a 4GHz 6 core desktop with AVX2 is around 30MT/s). Also, double check you are successfully picking up the build NEON variant (it should get selected automatically if you don't set anything, but the scalar fallback is going to be a lot slower).
> 
> In terms of format packing, the library doesn't do anything to help here - you just get the raw ASTC data. Packing into whatever container format you need is the caller's responsibility.

The Image's size is 720x1280 in PNG format. And the block size we set is 6x6.

We built the library with Xcode instead of CMake. I have no idea whether we enabled the NEON variant. 

The packing function I have found in astcenccli_image_load_store.cpp. It also worked on iOS including the packing and unpacking. I think there is no question on this side.

**Comment by solidpixel** [comment]
Closing.
