### ISSUE TITLE
Calling encode library from dotnet?

### ISSUE THREAD

**Issue by trasa-manticore** [ARM-software/astc-encoder#320]
Is it possible to compile astc-encoder in a library format that could be accessed from a C# application? Or would it be best to execute the `astcenc-*.exe` (with various flags) by using something like `System.Diagnostics.Process.Start`?

**Comment by solidpixel** [comment]
We don't provide any C# bindings out-of-the box, but the core codec is designed to be built as a library and has a plain C interface so creating bindings is definitely be possible.

I would definitely recommend going the "use as a library" route if you can. This allows you to create one compressor context that you can then reuse for compressing multiple images, which is definitely going to help overall performance (context creation is relatively expensive, as ASTC uses a lot a procedural data tables).

**Comment by solidpixel** [comment]
No follow-up, closing.
