### ISSUE TITLE
Tests fail to build: error: definition of implicit copy constructor for 'PolymorphicAction<testing::internal::ReturnVoidAction>' is deprecated because it has a user-declared copy assignment operator

### ISSUE THREAD

**Issue by yurivict** [ARM-software/astc-encoder#346]
```
/disk-samsung/freebsd-ports/misc/astc-encoder/work/astc-encoder-3.7/Source/GoogleTest/googlemock/include/gmock/gmock-actions.h:455:3: error: definition of implicit copy constructor for 'PolymorphicAction<testing::internal::ReturnVoidAction>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(PolymorphicAction);
  ^
/disk-samsung/freebsd-ports/misc/astc-encoder/work/astc-encoder-3.7/Source/GoogleTest/googletest/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
```

Not sure why you need to rebuild gtest when ready to use package exists.

Version: 3.7
clang-13
FreeBSD 13.1

**Comment by solidpixel** [comment]
> Not sure why you need to rebuild gtest when ready to use package exists.

We build for systems without package managers, so this is the least painful option.

**Comment by solidpixel** [comment]
I've updated `main` to use the latest (1.11.0) release of googletest, which should help, but not tried this on clang-13 yet.

**Comment by solidpixel** [comment]
Testing with the newer versions of Clang, and while the Googletest issue is solved there are still quite a lot of warnings flagged by clang-13. Will put up a separate PR to fix this.

**Comment by solidpixel** [comment]
PR #348 to fix the compiler warnings flagged by newer builds of Clang.

**Comment by solidpixel** [comment]
Merged. Let me know if you hit any more issues.
