### ISSUE TITLE
RGB 3 plane encoding with astenc

### ISSUE THREAD

**Issue by puffpio** [ARM-software/astc-encoder#350]
Does astc-encoder reduce the storage representation to 3 planes per block for RGB input?

From reading the ASTC spec it allows variable number of planes per block (eg 3 planes for RGB, 4 for RGBA)
The encoding guide (https://github.com/ARM-software/astc-encoder/blob/main/Docs/Encoding.md) states that setting the proper swizzle format of rgb1 kicks in some of these optimizations?

However looking at the store_image_block function (https://github.com/ARM-software/astc-encoder/blob/e83b0c8f67e7e704adb3f85c02d8cd547558fa31/Source/astcenc_image.cpp#L335)
It seems to always imply 4 planes regardless of the swizzle. Am I reading this correctly? It will always write 4 channel data even if setting the alpha swizzle to 1?

I was hoping to get a filesize reduction for RGB converted images by only using 3 planes vs 4.

**Comment by solidpixel** [comment]
> I was hoping to get a filesize reduction for RGB converted images by only using 3 planes vs 4.

ASTC is a fixed bitrate compression - you always get 128-bits per block, at whatever ASTC block size you choose to use. As a developer you can therefore control the stored compressed size by manually changing the block size you are using (ASTC gives developers a lot of block size choice here - it's the main feature of the format). This is totally orthogonal to the color format you are compressing - the only thing that matters for the output size is the block footprint. 

The internal compressed format can store fewer channels per color-endpoint on a per-block basis to avoid wasting bitrate on things that don't help image quality. This will manifest as better image quality rather than a smaller file (as the bitrate is constant for any given compression). 

HTH, 
Pete

**Comment by puffpio** [comment]
thanks! i'm really enjoying digging into how this all works

**Comment by puffpio** [comment]
so, if my thinking is correct: If I am compressing mostly textures w/o alpha channel (say a bunch of JPGs)

I should set the swizzle to rgb1 and that will help inform how to optimize

but I can also set the color weighting (-cw option on command line) to 1 1 1 0 to signal I don't care about any artifacts in the alpha channel and prioritize the RGB channels?

then likely the alpha plane would be dropped on each block. but potentially what's actually written into the alpha plane could be a bunch of garbage but it doesn't matter, since the rgb1 swizzle will ensure the GPU sees a 255 for alpha?

**Comment by puffpio** [comment]
grepping the codebase..it looks like

cw_r_weight
cw_g_weight
cw_b_weight
cw_a_weight

are set but never used at all

**Comment by solidpixel** [comment]
> I should set the swizzle to rgb1 and that will help inform how to optimize

Yes.

> but I can also set the color weighting (-cw option on command line) to 1 1 1 0 to signal I don't care about any artifacts in the alpha channel and prioritize the RGB channels?

Also yes, but if you guarantee a constant 1 alpha (either in the source data or via a load swizzle) it's unlikely to make any difference because the compressor will always drop the alpha anyway.

**Comment by solidpixel** [comment]
> grepping the codebase..it looks like ... cw_r_weight ... are set but never used at all

Assigned to `blk.channel_weight` in `compress_image()`, which is what the compressor uses internally.

**Comment by puffpio** [comment]
so an update from me, using the 'cw' option to set the alpha weight to 0 does slightly increase the ms-ssim output so it makes a difference!

however the 'cw' option overwrites the weights set when using the '-perceptual' option. so if you want to use perceptual AND devalue the alpha channel you have to set all the weights manually, which involves setting magic numbers.

it would be cool if when -perceptual sets weights, it checks if the encoding swizzle is rgb1 and if so then sets the alpha weight to 0

**Comment by solidpixel** [comment]
A quick test here shows that `-cw 1 1 1 0` slows down compression quite a bit, so I suspect the quality increase is due to the compressor making a more thorough search. Not 100% sure why - need to dig - but the gain in quality is pretty small and the performance loss is quite large.

**Comment by solidpixel** [comment]
The "why" is that we normalize the total error weight so the sum across the 4 channels is always the same. 

In the original case (`-cw 1 1 1 1`) the normalization ends up assigning a lower error contribution factor to RGB than in the updated (`-cw 1 1 1 0`) case.  The reason quality improves (and performance drops) is that the absolute significance of the RGB error increases, so the compressor has to try harder to find an encoding within target. 

So this is working as expected, at least given the current design.

**Comment by solidpixel** [comment]
Closing as completed - changes here are likely to disrupt existing quality settings which users are used to, and the gained consistency isn't a major usability improvement.
