### ISSUE TITLE
HDR flag is set inconsistently for loading KTX files

### ISSUE THREAD

**Issue by rovedit** [ARM-software/astc-encoder#358]
For KTX `is_hdr = bitness == 32;` is checked, whereas for any other container (e.g. DDS) `is_hdr = bitness == 16;` is checked.
This incorrectly assumes LDR source data if your data is loaded in as HDR in 16bit half-float.

But I would suggest looking for `is_hdr = bitness >= 16;` to recognize both 32bit floats and 16bit half-floats as HDR input.

**Comment by solidpixel** [comment]
Thanks for the bug report - fixed in ab77e7513ef66cbd6b333220cb22d4b86cb33ff3.
