### ISSUE TITLE
Support for 32bit float input

### ISSUE THREAD

**Issue by rovedit** [ARM-software/astc-encoder#359]
When compressing 32bit float data and decompressing it (using `-cH` HDR profile), the output doesn't resemble the input data anymore. When I load this data into my application, only a black picture is rendered.
There is also an assertion for 32bit float data triggered, when running the encoder in Debug mode. And, as referenced in [this issue](https://github.com/ARM-software/astc-encoder/issues/358), the HDR flag is (typically) not set for 32bit floats.

Instead, if I repeat the same process with 16bit float data, everything looks correct.

I checked R/RG/RGB/RGBA test data which should only render a green image (or red for R) and all exhibit the above described phenomenon. Here is the test data I used:
[fp16.zip](https://github.com/ARM-software/astc-encoder/files/9281624/fp16.zip)
[fp32.zip](https://github.com/ARM-software/astc-encoder/files/9281625/fp32.zip)

_Originally posted by @rovedit in https://github.com/ARM-software/astc-encoder/issues/352#issuecomment-1208057131_

**Note:**
I created a seperate issue for this problem as this had nothing to do with the original anymore.

**Comment by rovedit** [comment]
Also, the value range seems to be clamped to range [0, INF] for HDR data.
It would be good to have the full [-INF, INF] range of the 16bit soft-float format for general purpose data to be compressed.

**Comment by solidpixel** [comment]
The current loader doesn't understand 32-bit types at all - bitness is either 8 or 16. It's a relatively simple fix. 

In terms of supporting the full range this isn't possible - it's a limitation of the format. Unlike BC6, ASTC cannot encode negative values.

**Comment by rovedit** [comment]
Ah, I didn't know that with the negative values. Bummer, but thanks for the info.

**Comment by solidpixel** [comment]
Here is a PR that adds support for the 32-bit per component KTX input surfaces: #366 

Can you give this a go and let me know if it solves this problem. I'll handle decompressed KTX output surfaces at 32-bit per component in another PR.

**Comment by rovedit** [comment]
I checkout out to this PR and tested two 32-bit float textures (a 3D RGBA texture and a 2D RGB texture with only green color), but all render to a black picture when decompressed and loaded black into my application (I'm aware that the output is still 16-bit float).

When I investigate the buffer of my 16x16 test texture it now has alternating chunks of size 16 which all hold the same number (either 0 or 8192 which is presumably the 1.0 half-float representation in `uint16_t`).

**Comment by solidpixel** [comment]
Thanks - will dig more.

**Comment by solidpixel** [comment]
OK - PR now has the correct fix I hope. 

Sorry - I completely missed that our scanline copy routine was doing fp32-to-fp16 conversion on load, so I was loading the image for the codec as fp16 (correctly) but then telling it that the data was 32-bit floats. With this fix, the test images read back correctly when using `-th` now.
