### ISSUE TITLE
Support astcenc as a vcpkg

### ISSUE THREAD

**Issue by solidpixel** [ARM-software/astc-encoder#365]
Could you please support Vcpkg as well?
so `astcenc.h` can be used easily as a lib.
I opened a port issue on Vcpkg, https://github.com/microsoft/vcpkg/issues/23744 .

_Originally posted by @ylz-at in https://github.com/ARM-software/astc-encoder/issues/309#issuecomment-1077285405_

**Comment by solidpixel** [comment]
Rejecting for now - I don't have time to maintain the package management part of this.

**Comment by lotigara** [comment]
The current workaround for this is using the KTX package. It provides the KTX:astcenc-... target.
