### ISSUE TITLE
[Question] Can encoder be run on AWS Lambda?

### ISSUE THREAD

**Issue by ApprenticeGC** [ARM-software/astc-encoder#369]
I am trying to run the encoder prebuilt execution on AWS lambda which runs on Amazon Linux. It will have error saying that GLIBC 2.27 is required(Amazon Linux uses GLIBC 2.26). I am just wondering if I build the encoder on the environment installed with GLIBC 2.26, am I able to build it? Or the minimum requirement will be as stated GLIBC 2.27? Thanks.

**Comment by solidpixel** [comment]
If you rebuild from source it should be fine; the Linux binaries we provide are always going to have some dependency versioning problems unfortunately.  

When rolling your own it's recommended to use Clang, not GCC, as the binaries are 10-15% faster.
