### ISSUE TITLE
crash when decode image

### ISSUE THREAD

**Issue by AndrewChan2022** [ARM-software/astc-encoder#370]
platform: x64 macos

function: store_image_block

crash line: store_lanes_masked(reinterpret_cast<int*>(data8_row), data_rgbai, store_mask);

reason:
at image edge,  data8_row data is less than 16 byte, 
but store_lanes_masked will use 128bit, 
thus cause memory access crash.

**Comment by solidpixel** [comment]
It's a masked store - it shouldn't crash as the out-of-bounds writes should be silently dropped by the hardware.

* Which build of the compressor were you using (SSE2, 4.1, AVX2, etc)?
* Which macOS / CPU  model were you running on?
* Do you have a test image that reproduces this reliably?

**Comment by solidpixel** [comment]
Hmm, it looks like the SSE `maskmovdqu` instruction doesn't guarantee fault suppression for the masked lanes (the AVX2 version does). We'll need to replace that with a scalar fallback.
