### ISSUE TITLE
kram astc decoder looping indefinitely in single-thread decode

### ISSUE THREAD

**Issue by alecazam** [ARM-software/astc-encoder#377]
Looks like this code doesn't advance m_start_count, so I think this is the fix.  Feel free to close if this was already fixed.

```
     unsigned int get_task_assignment(unsigned int granule, unsigned int& count)
     {
         unsigned int base = m_start_count;
+        
+        // need to update start count in single-threaded case
+        // This is to match fetch_add in threaded case, but really should be done after test below
+        m_start_count = base + granule;
+       
         if (base >= m_task_count)
         {
             count = 0;
             return 0;
         }
                 
         count = astc::min(m_task_count - base, granule);
         return base;
     }
```

**Comment by alecazam** [comment]
That may not be the correct fix.  I seem to be missing the upper blocks of the astc decodes now.

**Comment by solidpixel** [comment]
I think this is code you added in Kram; it doesn't exist upstream. We only have a single `get_task_assigment()` function which always uses `m_start_count.fetch_add`.

**Comment by alecazam** [comment]
I only use encode/decode on a single-thread, and was trying to use eastl/fastl which don't have the best threading impls.    I had this note.   string instantiates 5 instances of string types, and that takes a while.  So was also trying to isolate that.   I know for a viewer, I should probably enable threading to decode multiple blocks at a time, but kram and my viewer share a library.  Sorry for the bother, I think I have a better emulation of fetch_add which returns the current value, and then adds to it.

#define ASTCENC_USE_THREADS 0
#if ASTCENC_USE_THREADS
    // these pull in string from system_error which is slow to instantiate on macOS
    #include <condition_variable>
    #include <mutex>
    #include <atomic>
#endif
