### ISSUE TITLE
Add prebuilt dynamic libraries to the releases

### ISSUE THREAD

**Issue by supermegadev** [ARM-software/astc-encoder#380]
I would like to use astc encoding in my python utility using ctypes if possible.
Do you have any plans to add dynamic library versions for windows, mac and linux to the releases as well?

Thanks

**Comment by solidpixel** [comment]
No plan to provide them by default at the moment. 

There is no off-the-shelf build support for in the CMake files, but the source code is already set up to allow designed to allow it. Build with `ASTCENC_DYNAMIC_LIBRARY` defined to export the DLL entry points for the codec..

**Comment by limburgher** [comment]
ASTCENC_DYNAMIC_LIBRARY doesn't seem to work with 4.1.0 to generate solibs. Do I need to use main or is there something else for Linux?

**Comment by solidpixel** [comment]
As above, it won't build them using the existing CMake build system. You'll need to provide your own CMake build for the .so, but if you build with ASTCENC_DYNAMIC_LIBRARY defined, you won't need to modify the source code.

**Comment by limburgher** [comment]
Sadly my cmake skills are limited. @supermegadev did you make any progress?

**Comment by solidpixel** [comment]
Latest `main` branch (will be in 4.4.0) now supports building shared objects by specifying `-DSHAREDLIB=ON` on the CMake configure step.
