### ISSUE TITLE
Multi-Threading decompression result in random white pixels

### ISSUE THREAD

**Issue by ArlexDu** [ARM-software/astc-encoder#381]
Hi,
I want to use multi-threading decompression in my project, and I use this way which is writing in astcenc.h
![image](https://user-images.githubusercontent.com/11871045/199017554-1e4139b1-0add-42c0-8974-4814637bee2f.png)
However, I find there are random white pixels in the result
![image](https://user-images.githubusercontent.com/11871045/199018471-350c29c9-06f0-46a8-b1ee-4ef00c0d7d60.png)
Does anyone know the reason？
By the way, using the decompress API is good in a single thread.
Thanks

**Comment by solidpixel** [comment]
Possible to share some more info about how you are setting up the input/output images and the contexts?

**Comment by ArlexDu** [comment]
Hi,

I want to use it in taskGraph which is a UE4 multi-theading Method.
Here is my code.
And the image's format is ASTC4x4

` 

      foreach image:
                auto f = Async(EAsyncExecution::TaskGraph, [this, image]() {
                                               decode(image);
                              });


` 
` 

      decode(imageData){
             // some code to prepare data...
             astcenc_context* my_context = nullptr;
             astcenc_config my_config;
             astcenc_config_init(ASTCENC_PRF_LDR, 
                      4,
                      4,
                      1,
                      ASTCENC_PRE_FAST,
                      ASTCENC_FLG_DECOMPRESS_ONLY,
                      &(my_config));
              astcenc_context_alloc(&my_config, 1, &my_context);
              astcenc_swizzle swizzle = { ASTCENC_SWZ_R, ASTCENC_SWZ_G, ASTCENC_SWZ_B, ASTCENC_SWZ_A };
              astcenc_image img;
              img.dim_x = width;
              img.dim_y = height;
              img.dim_z = 1;
              img.data_type = ASTCENC_TYPE_U8;
              void** data = new void*[img.dim_z];
              data[0] = outData;
              img.data = data;
              if (astcenc_decompress_image(my_context, inData, inLen, &img, &swizzle, 0) != ASTCENC_SUCCESS)
              {
                  delete[] data;
                  outLen = 0;
                  if (outData != nullptr)
                  {
                     free(outData);
                  }
                  return nullptr;
              }
              else
              {
                  delete[] data;
              }
              astcenc_context_free(my_context);
      }

`

**Comment by solidpixel** [comment]
What's the complete code for this in terms of the lambda capture? What type is "image", and where does "outData" come from?

**Comment by ArlexDu** [comment]
Hi Pete,
I update astcenc to the 4.2.0 version, now it run well in multi-threading!
Thanks for your information

**Comment by solidpixel** [comment]
Closing - issue fixed up using latest version.
