### ISSUE TITLE
`astcenc_config_init()` crashes when astc-encoder is compiled with AVX2 instructions on CPUs that don't support AVX2

### ISSUE THREAD

**Issue by gregschlom** [ARM-software/astc-encoder#384]
In theory, astc-encoder will [check for AVX2 support](https://github.com/ARM-software/astc-encoder/blob/026235b65e3480704599ec865d873dc0797b1156/Source/astcenc_entry.cpp#L685) during `astcenc_context_alloc()` and fail gracefully if the ISA isn't supported.

However, when AVX2 is enabled, it seems like the compiler uses AVX2 instructions in `astcenc_config_init()`, specifically [this line](https://github.com/ARM-software/astc-encoder/blob/026235b65e3480704599ec865d873dc0797b1156/Source/astcenc_entry.cpp#L533).

As a result, it crashes with `EXCEPTION_ILLEGAL_INSTRUCTION` even before the library has a chance to gracefully fail.

**Comment by solidpixel** [comment]
Thanks for the bug report. 

I've added the ISA and FP checks to `config_init()` as well as `context_alloc()` on latest `main`. This isn't a perfect solution - in theory nothing is stopping the ISA test function from using a more advanced SIMD instruction set - so I'll leave this open and try and improve that too.

**Comment by gregschlom** [comment]
Thanks for the quick fix! Much appreciated.

I suppose the ideal fix is to compile the ISA test functions separately (maybe as its own static library?), without any special instruction set, but not sure how much work that would be.

The quick fix seems to be sufficient for now.

**Comment by gregschlom** [comment]
Sorry, I wasn't able to actually test the fix myself since I don't have access to an old machine, but after shipping our updated app we're still seeing reports of `EXCEPTION_ILLEGAL_INSTRUCTION` crashes in the field, but now on [line 482](https://github.com/ARM-software/astc-encoder/blob/5628c6f10fa88f7d46e9f0b647c2b5ce6badbcaf/Source/astcenc_entry.cpp#L482) which is the very beginning of the function.

So I assume there's no good way to prevent the compiler from using SIMD instructions right away. The only way to fix would be to move the `astcenc_config_init()` function to a separate .cpp file, compiled without any extra instruction set flags.

Not sure how much work it would be for you guys. As a workaround, we will probably just do the instruction set checks on our side, before calling astcenc.

**Comment by solidpixel** [comment]
Footnotes - trying to work out how to test this in future:
* QEMU doesn't work - can hide CPUID flags and fail the software check, but won't fail if the code uses instructions the host supports.
* Intel SDE should work for this use case, but doesn't work under WSL, so need to check that on a native Linux machine.

**Comment by solidpixel** [comment]
Initial PR implementing the above:
* https://github.com/ARM-software/astc-encoder/pull/400
