### ISSUE TITLE
Binary usage license 

### ISSUE THREAD

**Issue by praveendath92** [ARM-software/astc-encoder#39]
The license file in the repo doesn't seem to be one of the standard Open Source License (like Apache or GPL). 

Could you please clarify if it permits the usage of the binaries in this repo for converting images from PNG to ASTC format? And using the resulting ASTC textures in a commercial application - essential not shipping the binaries but rather the ASTC output generated by it

**Comment by solidpixel** [comment]
> Could you please clarify if it permits the usage of the binaries in this repo for converting images from PNG to ASTC format? And using the resulting ASTC textures in a commercial application 

Yes, this is explicitly allowed under the definitions defined as "Authorised Use" in the license (see clause 1).

> Essential not shipping the binaries but rather the ASTC output generated by it

Redistributing the ASTC compressor binaries for the purposes outlined in license clause (1) is also allowed (see clause 2).

**Comment by praveendath92** [comment]
@solidpixel Thanks for clarification 👍
