### ISSUE TITLE
Add channel error weight rescaling

### ISSUE THREAD

**Issue by solidpixel** [ARM-software/astc-encoder#396]
Split from #394.

Today the compressor doesn't normalize user-provided custom channel error weights, so the absolute scaling applied to the real error is unbounded. For large channel weightings a user reports that can fail to sensibly compress blocks. The hypothesis is that because the error is scaled up so much that no block beats the minimum DEFAULT_ERROR error target needed to select an encoding during a trial.

The purpose of the channel weights is to bias the quality of the compressor to favor specific color components. However, the current behavior ALSO allows it to be overloaded as a general quality boosting tool (increase all channel weights making it harder to hit error target), which isn't really how it is intended to be used.

This ticket proposes adding channel weight normalization, ensuring that e.g. the channel weights sum to 4.0 which would (mostly) match the default scaling. Users using channel weights to prop up overall quality are directed to use `-dblimit` to solve that problem more cleanly than overloading the `-cw` option. 

Do we do a flat rescale to 4.0, or a rescale based on active channel count?
* The latter is conceptually cleaner.
* Rescaling so it sums to 4.0 "works", but would be a change for normal maps, which sum to 2.0 today. 
* Rescaling so it sums to active channel count "works", and is transparent for normals, but would be a change for luminance textures, which sum to 4.0 today.

**Comment by solidpixel** [comment]
Testing the latest main branch for this one, and I'm struggling to make this fail, even with very large -cw values.

**Comment by solidpixel** [comment]
I can make this completely fail, but only with values that are huge that the channel weights encode as an fp32 inf, at which point the failure mode is (as expected) to fall back to a constant color encoding. This seems plausible and unlikely in practice.

Closing as "won't fix" - issue caused by imbalanced error heuristics.

**Comment by andrewevstyukhin** [comment]
0.213 + 0.715 + 0.072 < 1.000 for floats, so it maybe the cause of inequality.
On other images I got nasty gray patches for integer weights.

**Comment by solidpixel** [comment]
If the grey patches are specifically related to the magnitude of the weights (rather than the channel ratio) can you share an exact reproducer? I can't get this to fail without extreme magnitudes, so I think the compressor is working as expected given the weights provided.

**Comment by andrewevstyukhin** [comment]
Sure )

Source is:
![air](https://user-images.githubusercontent.com/7923719/214533640-1b7f70bb-50af-4fe4-926f-3c121baa4af0.png)

Bad invocation `astcenc-avx2.exe -tl air.png air5x5.png 5x5 -thorough -yflip -cw 213 715 072 1000` produces:
![air5x5](https://user-images.githubusercontent.com/7923719/214533780-62a3f9ad-efcc-453f-ad98-1b2677353b61.png)

Good invocation `astcenc-avx2.exe -tl air.png air5x5.png 5x5 -thorough -yflip -cw 0.213 0.715 0.072 1.000` results are:
![air5x5](https://user-images.githubusercontent.com/7923719/214534005-48ebc21e-8bd7-4d58-8806-5667bbce56ad.png)
