### ISSUE TITLE
“Undefined reference” when calling functions defined in "astcenc.h"

### ISSUE THREAD

**Issue by MaxLykoS** [ARM-software/astc-encoder#399]
This is a question.
Im trying to build .so file to run compression code on android. I built project via cmake gui and create an android shared library project besides whats left, and i followed example code, which needs to include "astcenc.h" to call functions like "astcenc_config_init()" and "astcenc_context_alloc()" etc. but all of them are "undefined reference" showed by the compiler.
What did I miss?

**Comment by solidpixel** [comment]
Ensure that the ASTC library is named `libastcenc.so`  and that you have added the library to your linker command i.e. `-lastcenc`
