### ISSUE TITLE
What is the command line option to get BC4 equivalent ASTC output?

### ISSUE THREAD

**Issue by manaskulkarni786** [ARM-software/astc-encoder#40]
I know -normal_psnr roughly maps to BC3nm and you use red and alpha channels in the shader.

To get a single channel output, is it correct to use "-ch 1 0 0 0 -esw r000-dsw r000" as the set of switches? Is the -mask switch going to be of any help here?

Thanks

**Comment by solidpixel** [comment]
For single channel textures in terms of getting the best quality for your bitrate you want the encoder to use the endpoint for luminance blocks with no alpha (i.e. alpha always == 1). For this you want to replicate the single channel color input to the three color channels, and force alpha to 1.

`-esw rrr1 -dsw r000 -ch 1 0 0 0`

Note that the `-dsw` settings don't influence how the compressed image is generated; they are just used to swizzle outputs in the software decompressor when emitting a TGA image.

**Comment by solidpixel** [comment]
Channel mapping equivalence documentation added as part of #47.

**Comment by solidpixel** [comment]
Closing, PR now merged.
