### ISSUE TITLE
3D image decompression

### ISSUE THREAD

**Issue by terier** [ARM-software/astc-encoder#403]
Hello,

the CLI currently does not seem to support decompressing a 3D image into a sequence of slices, which would effectively reverse the compression operation. Would you consider allowing the -zdim flag for the decompression as well? Or simply output a sequence of slices whenever zdim > 1?

Thanks!

**Comment by solidpixel** [comment]
Thanks, this sounds like a good improvement. I'd propose just emitting slices if the output format is 2D (e.g. PNG) and the image has zdim > 1.
