### ISSUE TITLE
`color_uquant_to_scrambled_pquant_tables` not defined for decompress only build

### ISSUE THREAD

**Issue by unclejimbo** [ARM-software/astc-encoder#404]
The definition of `color_uquant_to_scrambled_pquant_tables` is guarded by `#if !defined(ASTCENC_DECOMPRESS_ONLY) #endif` but used in astcenc_symbolic_physical.cpp unguarded. v4.3.1

**Comment by solidpixel** [comment]
Thanks for the bug report. The Release build we have in CI wasn't failing because LTO was stripping out the dead code before linkage fails.
