### ISSUE TITLE
Warning overrides no longer valid with gcc 11 

### ISSUE THREAD

**Issue by MarkCallow** [ARM-software/astc-encoder#406]
I am trying to compile the encoder on Ubuntu 22.04 on an arm64 CPU with gcc / g++ 11.3. I get the following warnings:

```
cc1plus: note: unrecognized command-line option ‘-Wno-reserved-identifier’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-shift-sign-overflow’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-implicit-int-conversion’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-atomic-implicit-seq-cst’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-c++98-c++11-compat-pedantic’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-c++98-compat-pedantic’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
```

I'm using a fairly old commit in my `git subrepo` clone: c9424dcfc5c9684717a3f18166be64ab7baed3fa. It is possible you've fixed these since then but I could not find any matching issues or PRs. The ignore directives are set in `Source/cmake_core.cmake` for any non MSVC compiler.

I am getting quite a few errors too such as

```
/home/mark/Projects/khronos/github/KTX-Software/lib/astc-encoder/Source/astcenc_vecmathlib_neon_4.h:999:32: error: cannot convert ‘int32x4_t’ to ‘signed char’ in initialization
  999 |         int8x16x4_t table { t0.m, t1.m, t2.m, t3.m };
```

I'll open another issue for those unless you tell me they are already fixed.

I don't have any problem compiling for macOS arm64 with Xcode / Clang.

**Comment by solidpixel** [comment]
Let me double check. I don't think we're testing that GCC version in our CI.

**Comment by solidpixel** [comment]
Confirm we're clean for GCC 11.3 for x64.

**Comment by MarkCallow** [comment]
> ... so I think this should be good if you can update to the latest

I'll try it as soon as I get to convenient point.

By the way the commit I am currently using is clean for Windows on both x64 and arm64 with MSVC 19.34.31944.0 and Clang 15.0.1 and with Clang 14 on both x64 and arm64 on macOS. It is only GCC for aarch64 that I am having problems with.

**Comment by solidpixel** [comment]
I seem to remember fixing something, so if you want a backport to have the version you have now let me know, and I can share a patch.

**Comment by MarkCallow** [comment]
I just pulled top of main. It now compiles without a problem. If I find an issue during testing that may require a backport of the fix, I'll reopen this.
