### ISSUE TITLE
Improve universal support for macOS

### ISSUE THREAD

**Issue by solidpixel** [ARM-software/astc-encoder#408]
The current macOS support only handles a single x86 build slice, but it should be possible to support a single Universal binary that supports arm64 (NEON), x86_64 (SSE4.1), and x86_64h (AVX2) slices. 

This was attempted in PR #405, but the current build doesn't really cope with it as we try to build all slices in a single compile. Given the need for different compile options for each x86 slice we really need to compile multiple binaries with a custom universal build step that uses `lipo` to merge the requested slices into a single universal binary.

**Comment by solidpixel** [comment]
Current proposal.

Configure will expose an explicit option to manage if you want a universal binary `-DASTCENC_UNIVERSAL_BUILD` which will be `ON` by default for macOS builds, but you can manually set of `OFF`. 

For a Universal binary the ISA selection will determine which slices are enabled:

* ASTCENC_ISA_NONE/ASTCENC_ISA_NEON -> arm64
* ASTCENC_ISA_AVX2 -> x86_64h
* ASTCENC_ISA_NONE/ASTCENC_ISA_SSE2/ASTCENC_ISA_SSE41 -> x86_64

It will be an error for a universal binary if you specify more than one ISA per slice.
It will be an error for a universal binary if ISA slice mismatches with CMAKE_OSX_ARCHITECTURES (if its set).

The build will stop trying to build all variants in a single compile, and build each ISA separately. A custom build rule will wrap `lipo -create` to build the universal binary that was requested. (edited)

**Comment by solidpixel** [comment]
@pthariensflame Are you able to give this a try - I think this should do what you wanted.

**Comment by pthariensflame** [comment]
@solidpixel Sorry for being unavailable!  I should get around to testing this in the next couple of days.  Thank you so much!

**Comment by solidpixel** [comment]
No worries - thanks for the information about the `x86_64h` slice - I didn't know that existed =)
