### ISSUE TITLE
I can't open the program

### ISSUE THREAD

**Issue by TheTSS** [ARM-software/astc-encoder#418]
Sorry, I'm new to this. When I run the program it closes itself. How can I open the program?(i'm using Windows)

**Comment by solidpixel** [comment]
The standalone compressor is a command line utility - no GUI - so you need to use it from either a Windows "cmd" or PowerShell terminal window.

**Comment by TheTSS** [comment]
how do I do that? I can open cmd but I don't know what to do to start the program there. Is there a tutorial to do it?

**Comment by solidpixel** [comment]
Assuming you have the compressor binary and the image you want to compress in a directory called `C:\Work`, run these in the command terminal.

Something like this to compress (change file names as needed):

```
cd C:\Work
.\astcenc-avx2.exe -cl input.png output.astc 6x6 -medium
```
... and this to uncompress back (change file names as needed):

```
.\astcenc-avx2.exe -dl input.astc output.png 6x6 -medium
```

If your computer doesn't support AVX2 you might need to use `.\astcenc-sse41.exe` instead.

HTH, 
Pete

**Comment by TheTSS** [comment]
i don't have C:\Work directory. How can I create it in cmd?

Thank you again for the reply.
