### ISSUE TITLE
Compile fails on Android NDK after PR #417

### ISSUE THREAD

**Issue by MarkCallow** [ARM-software/astc-encoder#419]
Building with Android NDK r21e, get

```
clang++: error: unknown argument: '-ffp-model=precise'
```

I've not been able to track down the Clang version. Cmake skips its usual working c compiler check so no information is printed. According to the NDK [changelog ](https://github.com/android/ndk/wiki/Changelog-r21)

```
Updated Clang and LLD to r365631
```

I have no clue how to translate r365631 into a real version number.

I'll try a later NDK, if I can.

**Comment by MarkCallow** [comment]
It works with the latest NDK, r25c.

**Comment by solidpixel** [comment]
r21e is ancient - do we really need to keep supporting it?

**Comment by solidpixel** [comment]
```
android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --version
Android (7019983 based on r365631c3) clang version 9.0.9
```

**Comment by MarkCallow** [comment]
Thanks for the rapid fix. I'm not an Android developer so can't answer about the worth of putting in the workaround. 2 years isn't that old. I certainly wouldn't describe it as ancient. On the other hand Clang has moved on 6 major versions in that time and developers probably have moved with it.

**Comment by solidpixel** [comment]
Yeah, ancient was probably overstating it =) I actually thought it was a 2019 compiler, but it's actually 2021.
