### ISSUE TITLE
Encode 1 pixel height of png image file

### ISSUE THREAD

**Issue by liuliqianxiao** [ARM-software/astc-encoder#428]
When I use astcenc to encode one pixel height of png file, I get wrong height of compressed texture, 
For exalple, the original image resolution is 192x1, the result compress texture resolution is 192x0.
My command args like this: -cl 4x4 -fast -pp-premultiply

**Comment by solidpixel** [comment]
What output format are you writing and how are you reading the file to determine that it's the wrong height? Testing here and inspecting with a hex editor and both `.astc` and `.ktx` looks fine.

**Comment by liuliqianxiao** [comment]
[assets.zip](https://github.com/ARM-software/astc-encoder/files/11934189/assets.zip)

Yes, I use the latest compressor version.
In the zip file, .png file is the original image file, .astc file use the latest compressor , .ktx file generate by texture_compress node`s npm library .

How I get .astc file resulotion (Node.js code): 
`
let buffer: Buffer = fs.readFile("Your astc file path");
let view: DataView = new DataView(new Uint8Array(buffer).buffer);
let w: number = view.getUint8(7);
let h: number = view.getUint8(8);
`

**Comment by solidpixel** [comment]
Looks like you are reading the wrong data for height. For the `.astc` file the width is bytes 7-9 and height is bytes 10-12 (assuming zero indexed). See https://github.com/ARM-software/astc-encoder/blob/main/Docs/FileFormat.md.

```
let buffer: Buffer = fs.readFile("Your astc file path"); 
let view: DataView = new DataView(new Uint8Array(buffer).buffer); 
let w: number = view.getUint8(7); 
let h: number = view.getUint8(8); // This needs to be 10
```

Note that in general you need to decode dimensions as the three byte triple and reconstruct: 

```dim[0] + (dim[1] << 8) + (dim[2] << 16);```

Reading single bytes will break for any resolution over 255 pixels.

**Comment by liuliqianxiao** [comment]
Sorry for disturbing you， It`s my mistake~~~~~

**Comment by solidpixel** [comment]
No problem, happy to help.
