### ISSUE TITLE
retro studios txtr textures

### ISSUE THREAD

**Issue by TROguz** [ARM-software/astc-encoder#436]
Is astc tool supports txtr textures? It didnt work for me or I couldn't make it. Txtr textrues using astc encoder. There is a font file which i need to edit and it's compressed. If I send example file would you check it out?
[TXTR.zip](https://github.com/ARM-software/astc-encoder/files/13061983/TXTR.zip)

**Comment by solidpixel** [comment]
No native support for game-specific packing formats, and not something we'd be willing to support given there are literally hundreds of them. 

You'd need to extract the raw ASTC stream and add in the header to make a valid ".astc" file.

https://github.com/ARM-software/astc-encoder/blob/main/Docs/FileFormat.md
