### ISSUE TITLE
Compress/decompress progress callback

### ISSUE THREAD

**Issue by dhalsimax** [ARM-software/astc-encoder#450]
Hi all,

It woud be nice to have a callback for compression/decompression tracking to make the caller aware of the progress. An idea would be to add a well prototyped function pointer to the astcenc_config struct as a member. Such member, if not null, would be programmatically called in the main loops of compress_image and astcenc_decomoress_image with some blocks_done and blocks_total parameters.

**Comment by solidpixel** [comment]
I don't see many scenarios where this is really necessary. How slow is compression on your system?

For typical compression settings and image sizes, compression is normally only 1-2 seconds per image.  Decompression is two orders of magnitude faster than that.

For a typical asset compression workflow (many textures, many mipmap levels) a progress bar is more usefully done based on the completion of the overall texture pool, rather than single images.

**Comment by dhalsimax** [comment]
Oh yes you maybe right. Anyway not many have lots of cores and ghz, For example I have embedded the library in a tool that compress, for only a 2D game, hundreds of 1024x768 textures and in exaustive quality 8x8 block taking almost 160 seconds per texture on an older i7-7700HQ dell's notebook using multithreading. I also have dozen of 8k textures taking much much more. Think that also moving resolution of such 2D games in the near future above in full hd would exponentially add seconds for hi res textures.

**Comment by solidpixel** [comment]
True, `-exhaustive` compression can be very slow. IMO the image quality benefit for real game usage probably doesn't justify the improvement over `-thorough`.

**Comment by dhalsimax** [comment]
You maybe right too don't mind. I'm osbessed by verbosity since I've switched from the incomprehensible window's background hd crunching to the well verbose linux some decades above. From a conspiracy perspective, I believe that Microsoft has been pressuring manufacturers for years to no longer include the hard disk activity LED in their computers. So jokes aside, feel free to close this request I will buy a faster notebook soon. It was a pleasure, regards.

**Comment by solidpixel** [comment]
Leave this open - will take a look at adding it, as it's not a lot of work to do so.

**Comment by solidpixel** [comment]
Try this PR: #451

I only added callback support for compression - decompression really doesn't need it.

**Comment by solidpixel** [comment]
Merged.

**Comment by dhalsimax** [comment]
Nice. Thanks.
