### ISSUE TITLE
How to encode RGB+A with dual weight planes?

### ISSUE THREAD

**Issue by MartinCaine** [ARM-software/astc-encoder#459]
I've been investigating an issue with conversion to ASTC for some textures in our pipeline, and we're finding horrible alpha corruption in an RGBA texture (RGB channels look good, far less blocky than the DXT equivalent). I've read that ASTC supports dual-plane weights, with the ASTC User Guide explicitly stating the use case scenario that we have (our alpha values are a sort of mask, containing luminance values, not correlated to the RGB data).

I'm struggling to see how to create a texture in this way with the astc-encoder though, is it even possible? The -cw option gets us much nicer results if we specify a huge number in the A weighting, but there are still errors in the output (specifically, blocks of pure black (or zero alpha) in the output image). The DXT equivalent has no zero values in these areas.

Following text direct from the ASTC User Guide:

> **5.12 Dual-plane weights**
> Using a single weight for all color channels works well when there is good correlation across the channels, but this is not always the case. Common examples where we might get low correlation include:
> • Textures storing RGBA data. Alpha masks are not usually closely correlated with the color value.
> • Textures storing normal data. The X and Y normal values often change independently.
> ASTC provides a dual-plane mode, which uses two separate weight grids for each texel. A single channel can be assigned to a second plane of weights, while the other three use the first plane of weights.
> The use of dual-plane mode can be chosen on a per-block basis, but its use prevents the use of fourcolor partitions. This is because there are not enough bits to concurrently store both an extra plane of weights and an extra set of color endpoints.

**Comment by MartinCaine** [comment]
I did find this post, which looked promising, the -a 1 command line option vastly improves quality, but the problem we're seeing is any zero values in this channel are multiplied in to the lighting which creates pure black output when rendering.

Here's a portion of our source uncompressed image, A values as greyscale, ramped up to show the very smallest values at scale:
![image](https://github.com/ARM-software/astc-encoder/assets/8378093/b96c0f0f-17da-407d-aca5-68d5f4d92584)

Here's the same from an astc converted using 4x4 -exhaustive:
![image](https://github.com/ARM-software/astc-encoder/assets/8378093/5b37a782-eb7f-498b-bab9-dd485aa8d7ef)

The same with the -a 1 option:
![image](https://github.com/ARM-software/astc-encoder/assets/8378093/3401fb65-29a8-4819-926c-8e6431ff8b59)

And finally with a ridiculous weight for A (-cw 1 1 1 1000000):
![image](https://github.com/ARM-software/astc-encoder/assets/8378093/82abbf8b-12d4-4207-b31b-540087a6d541)

There are still black parts appearing. If there is a way to clamp these to be non-zero that would be ideal, even if it means editing the code to do this for these textures at conversion time. I'm reluctant to go adding in min clamp in to our shaders, but it's looking like that may work, with the bottom image here.

**Comment by solidpixel** [comment]
The dual plane mode is automatic, so there is nothing to turn on manually - the compressor will choose which color component is the dual plane dynamically on a per-block basis. 

Are you able to share the source texture and the command line you are using? If you can't share the image publicly, please feel free to get in touch via performancestudio@arm.com.

**Comment by solidpixel** [comment]
Some handy ImageMagick commands:

```
// Crop a smaller test image
convert in.png -crop 256x256+256+768 in-crop.png

// Extract alpha to a luminance image
convert in.png -channel A -separate in_sep_3.png

// Rescale the low range to make it more visible. e.g. 16x
convert in_sep_3.png -fx '16*u' in_sep_3s.png
```

**Comment by solidpixel** [comment]
Interesting single block reproducers:
![in_sbr_0](https://github.com/ARM-software/astc-encoder/assets/23016617/c223b1b1-6cf3-402e-ac29-97a300568c64)

**Comment by solidpixel** [comment]
Discussed offline. Summary for anyone finding this issue later is that we didn't find a better way to make the the compressor to behave better, so the best option we came up with was to add a simple clamp to the shader code sampling the texture.
