### ISSUE TITLE
The png do not support to load

### ISSUE THREAD

**Issue by liumazi** [ARM-software/astc-encoder#463]
This condition is not met, in wuffs-v0.3.c
`if (self->private_impl.f_seen_trns || (self->private_impl.f_color_type > 3) || ((self->private_impl.f_color_type == 3) && !self->private_impl.f_seen_plte)) `
[MakeMirAtlasFromAgePreview.zip](https://github.com/ARM-software/astc-encoder/files/14988204/MakeMirAtlasFromAgePreview.zip)

**Comment by liumazi** [comment]
Use the TPngObject in Delphi to created the PNG.

**Comment by solidpixel** [comment]
> And, if use astcenc.exe 1.3, will prompt: "Failed to load image xx.png, Reason: tRNS with alpha"

The older release used stb_image to load images.

**Comment by solidpixel** [comment]
The latest Wuffs stable release doesn't fix this, so I've raised an issue upstream to see if they can support this use case in future, but the main problem here is that the image is technically out-of-spec (a tRNS chunk isn't allowed for RGBA color type images).

**Comment by solidpixel** [comment]
Upstream did a super-quick fix ❤️, so I'll update shortly.

**Comment by solidpixel** [comment]
Fixed in 56395a6fcecaac81ee7c3f03d86dc3c7689f6816
