### ISSUE TITLE
The alpha channel is painted black during compression

### ISSUE THREAD

**Issue by matsuzaki215** [ARM-software/astc-encoder#464]
The transparent areas are blacked out, when an image with transparent areas (sample.png) is compressed with the following command.
How can I solve this problem?

```
# add -yflip option because the image was inverted in my environment.
$ astcenc -cs sample.png sample.astc 6x6 -medium -yflip
```

The following images are comparing images before and after conversion on Unity.
※ Sry, If this is a problem with the Unity settings.

### original image (png)
![original image (png) ](https://github.com/ARM-software/astc-encoder/assets/40729872/4a261b9c-adb0-44d6-bf47-77a7dd6367c0)

### encoded image (astc)
![encoded image](https://github.com/ARM-software/astc-encoder/assets/40729872/25d971b2-bb5e-425e-91a8-645ccdcf0dac)

**Comment by solidpixel** [comment]
I don't think this is a compressor problem (or at least, no longer reproduces with the latest release). 

Decompressing with the command line seems to give the right result on a transparent PNG I have locally:

```
./astcenc-avx2 -cs repro.png out.astc 6x6 -medium -yflip
./astcenc-avx2 -ds out.astc out.png
```

**Comment by solidpixel** [comment]
In Unity when you import the texture what is the Alpha Source option set to in the import settings? I think that needs to be set to Input Texture Alpha.

**Comment by matsuzaki215** [comment]
@solidpixel 
Thank you for your reply.

> What version of the compressor are you using?

I built `astcenc` from source code at main branch so its maybe latest version.

> Can you share the input texture and the generated output astc file?

Sorry I can't attach astc file to github comment here.

> In Unity when you import the texture what is the "Alpha Source" option set to in the import settings? I think that needs to be set to "Input Texture Alpha", with the "Alpha Is Transparency" option ticked.

When I import astc file to Unity, that setting "Alpha Is Transparency" is not available.
![sc](https://github.com/ARM-software/astc-encoder/assets/40729872/e74bf6fc-1cca-4138-b128-f382b9a7d1f2)

When I import original png,  "Alpha Is Transparency" is available.
![sc2](https://github.com/ARM-software/astc-encoder/assets/40729872/c4d6c74e-2259-4e67-979f-088a0542b4cd)

**Comment by matsuzaki215** [comment]
@solidpixel 

As you pointed out, the "Alpha Is Transparency" setting seems to toggle between transparent and black in Unity.
However, it appears that the setting is not available when the astc image is loaded.

Please wait a little while before trying to check via the application in production, and if it is transparent I will close this issue.

**Comment by solidpixel** [comment]
A local check would be to decompress the `.astc` image back to a `.png` with the command line tool (i.e. `astcenc -ds ...`). If that's transparent then this is definitely a Unity integration issue.

**Comment by matsuzaki215** [comment]
@solidpixel 

Solved!

I import the astc image into my application and confirmed that it is transparent without any problems.
In other words, the Unity environment (the way it is shown) was the cause.
Thank you for your supports!!

**Comment by solidpixel** [comment]
Great, thanks for confirming. Closing.
