### ISSUE TITLE
4.8.0 has "possible loss of data warning" in astcenc_find_best_partitioning.cpp

### ISSUE THREAD

**Issue by MarkCallow** [ARM-software/astc-encoder#470]
At line 433 in this code

```
	// Create a running sum from the histogram array
	// Cells store previous values only; i.e. exclude self after sum
	unsigned int sum = 0;
	for (unsigned int i = 0; i < texel_count; i++)
	{
		uint16_t cnt = mscount[i];
		mscount[i] = sum;      // <==  Assigns unsigned int to uint16_t.
		sum += cnt;
	}
```

We have warnings as errors set so it breaks our build. This is with VS2022 latest cl. ClangCL doesn't raise this warning.

**Comment by Dreamer1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by MarkCallow** [comment]
@Dreamer1 please repeat in English.

**Comment by MarkCallow** [comment]
> @Dreamer1 please repeat in English.

Never mind. It's an out-of-the-office auto-reply. @solidpixel I suggest you delete this and the previous 2 comments, if you can.

**Comment by solidpixel** [comment]
Thanks Mark - will get that one fixed tomorrow.
