### ISSUE TITLE
Despite ASTCENC_INVARIANCE ON, results on M2/Neon (macOS, clang) differ from X86_64/AVX2 (Ubuntu, GCC)

### ISSUE THREAD

**Issue by MarkCallow** [ARM-software/astc-encoder#474]
Probably not just limited to the 2 platforms mentioned. Unfortunately GitHub Actions has managed to completely break Windows builds with their 20240603.1.0 runner image so I cannot investigate further at present.

I don't think this is new in 4.8.0.

By results differ I mean the encoded data has slight differences such that memcmp fails.

**Comment by solidpixel** [comment]
Thanks Mark, I'll take a look. 

This usually ends up being compiler version specific, so if you can share the specific compiler versions that would be great.

Do you have an input image and CLI command line that repros this that you can share?

**Comment by solidpixel** [comment]
P.S. floating point was a mistake ;) I'm so very tempted to try and rewrite this as an integer core.

**Comment by solidpixel** [comment]
@MarkCallow Are you able to share more info on how to repro this one, or can we close?

**Comment by MarkCallow** [comment]
I need to do more investigation. Sorry for dropping the ball.

**Comment by solidpixel** [comment]
No worries. I'm looking to line up a 4.9 maintenance release for ~September, so if there is a need to do something would be good to know in the next couple of weeks.

**Comment by solidpixel** [comment]
Closing - old issue with no repro. Please feel free to reopen if you can share more information on how to reproduce.

**Comment by Dreamer1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
