### ISSUE TITLE
KTX2 format support for output textures

### ISSUE THREAD

**Issue by Andreyogld3d** [ARM-software/astc-encoder#475]
Hi! We need to add KTX2 format support for output textures
https://registry.khronos.org/KTX/specs/2.0/ktxspec.v2.html

**Comment by solidpixel** [comment]
To support this use case, the codec has been integrated into the KTX tools as a compressor backend, so this is already possible via https://github.com/KhronosGroup/KTX-Software

**Comment by solidpixel** [comment]
Not against supporting it, but it's likely most full asset pipelines will also need other functionality that we do not support, such as mipgen and multi-surface packing. In my experience most developers either use a wrapper tool, such as the KTX-Software, or build their own pipeline around the core codec library. 

I'm not trying to support everything here - it doesn't seem necessary given other options exist.

**Comment by solidpixel** [comment]
Rejecting for the time being, given that using KTX-Software provides this functionality (and more) with astcenc available as a backend.
