### ISSUE TITLE
ASTC encoder output is resulting in a flipped image.

### ISSUE THREAD

**Issue by SudarshanShetty1796** [ARM-software/astc-encoder#476]
Hello,
I'm using a MacBook Pro 2019 model, where I have tried the following command on a PNG image. The compression worked successfully, but the resulting output is flipped 180 degrees. Why is that? Am I missing anything here?

`./astcenc -cs /Users/sudarshanshetty/Downloads/Avatar_Witch.png example.astc 4x4 -medium     
`

Original image:
<img width="1161" alt="Screenshot 2024-06-20 at 11 19 10 AM" src="https://github.com/ARM-software/astc-encoder/assets/129433402/19a5d1b3-19c3-4685-ad0d-aa10d71de67a">

ASTC encoder output image:
<img width="1162" alt="Screenshot 2024-06-20 at 11 20 37 AM" src="https://github.com/ARM-software/astc-encoder/assets/129433402/bcf2d156-215f-47d1-b497-554bd5be43d1">

**Comment by solidpixel** [comment]
Ask Apple. How to interpret and present the decompressed image is up to the viewing application. 

The compressor doesn't flip the image, and by convention the origin is top left corner. Looks like the thumbnail preview is using a bottom left corner origin.

**Comment by SudarshanShetty1796** [comment]
I don't think it is a thumbnail preview issue. If I decode it back with the ASTC decoder, the image gets rotated back to the original orientation. Additionally, I'm seeing the same flipping issue when importing it into the Unity game engine.

**Comment by solidpixel** [comment]
ASTC doesn't flip the image unless you tell it to. PNG has a top-left origin. ASTC, by convention, has a top-left origin. We don't flip the data.

If the viewing application decides to interpret the data as a bottom left origin it's nothing to do with the texture format.

If you want to use textures in a system with a bottom left origin you will need to use `-yflip`.

**Comment by SudarshanShetty1796** [comment]
Cool, got it.

> -yflip

 was the solution, thanks.

**Comment by solidpixel** [comment]
Also more that origin is API dependent - DX/Vulkan is top left, GL/GLES is bottom left, so YMMV ...
