### ISSUE TITLE
clang 20 warns about both -ffp-model=precise and -ffp-contract=off being set.

### ISSUE THREAD

**Issue by MarkCallow** [ARM-software/astc-encoder#499]
clang 20 gives the following warning which, since my project sets `-Werror`, results in the build stopping:

```
clang++: error: overriding '-ffp-model=precise' option with '-ffp-contract=off' [-Werror,-Woverriding-option]
```

It looks like astcenc is intentionally setting both options as it is done for several platforms. Am I correct? If so it will be necessary to silence the warning. Please update the build to do this. How do you recommend I do this in the meantime: command line option or pre-processor directive?

The clang 20 Users Manual says

"Note: If your command line specifies multiple instances of the -ffp-model option, or if your command line option specifies -ffp-model and later on the command line selects a floating point option that has the effect of negating part of the ffp-model that has been selected, then the compiler will issue a diagnostic warning that the override has occurred."

**Comment by solidpixel** [comment]
Honestly, I consider this a Clang bug.

"We give you two separate command line options for a good technical reason, but then we'll emit a spam log message if you actually use one of them ..." just sounds like a lousy design choice on the Clang side. 

Using precise without contraction is fairly standard practice for any software that wants cross-platform invariance.  Falling back to `strict` implies a bunch of other behavior around `fenv()` and exception traps that is generally unwanted.

**Comment by solidpixel** [comment]
I don't have Clang-20 set up locally yet - does this ⬆️ fix it?

**Comment by MarkCallow** [comment]
@solidpixel, The workaround works but note that I only testing building the encoder not the tests.

I agree with you that this is a spam warning. I am concerned that setting `-Wno-override-option` may override some other warning where it is important. I suggest opening an issue in the clang/llvm GitHub repo.

While testing your fix I discovered that I have the FP option settings messed when compiling my libktx sources. My sources still compiled with clang 20. Turns out I wasn't setting the options at all. May be related to my issue in #474. Will let you know.

**Comment by solidpixel** [comment]
Adding `-Wno-unknown-warning-option` was a deliberate choice because recent generations of compilers are increasingly "chatty" and keep adding new informative warnings every release. It's almost impossible to test and stay on top of the them all without build breakages whenever someone tries a new compiler or CPU build target.
