### ISSUE TITLE
Crashes in astcenc_compress_image on Windows x64 when using a "Release" version of the library

### ISSUE THREAD

**Issue by Jhonnyg** [ARM-software/astc-encoder#530]
As the title suggests, I get a segfault somewhere inside the library, but only when I compile the library using a release config. It works fine on all other platforms, and on Win32 if I compile it in debug instead. 

This is the stacktrace:
![image](https://github.com/user-attachments/assets/ebc530dd-637c-4f57-9ace-a5b2a599cb84)

For the record, this is how I build the library (NOTE: It's currently set to Debug due to this issue!):
https://github.com/defold/defold/blob/astc-compression-in-texc/share/ext/astcenc/build_astcenc.sh

And this is the small piece of code that encodes into ASTC, which is taken from the samples found in this repo:
https://github.com/defold/defold/blob/29ead6d9dac34d6263b84b747b0b4f405c1c9610/engine/texc/src/texc_enc_astc.cpp#L88

Debug vs Release suggests that perhaps variables are uninitialized, but the stack trace seems to point to something related to multithreading? I run with just 1 thread, so I don't know if this is a red herring or not.

**Comment by Jhonnyg** [comment]
VS2022, this is what's getting picked up from cmake:
C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe

**Comment by solidpixel** [comment]
Thanks - will take a look.

**Comment by solidpixel** [comment]
So far I've failed to repro a crash trying to align our standalone example build with your library wrapper, can you provide a bit more info on how you are using this?

- Is the crash 100% reproducible on all test runs?
- Does it happen with all input images/resolutions?
- Does it happen on the first image you compress, or subsequent ones?

---

It's not causing this problem, but one thing I did note is that your code does this before calling `astcenc_config_init()`. This was a bug in our original Example project that I need to fix.

``` 
        astcenc_config config = {};
        config.block_x = block_x;
        config.block_y = block_y;
        config.profile = profile;
        config.progress_callback = astcenc_progress;
```

The init call will overwrite your config struct, so tt doesn't need zero-init and if you want to set a progress callback you'll need to modify the structure after init(), not before.

**Comment by solidpixel** [comment]
Hmm, this sounds like it might be related:

* https://stackoverflow.com/questions/78598141/first-stdmutexlock-crashes-in-application-built-with-latest-visual-studio

Are you mixing and matching Windows toolset versions? Can you try defining `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` for your library build to see if that helps?

**Comment by Jhonnyg** [comment]
Ah, yes you are right! Good catch! It turns out my toolset version was not the same as we use on CI and when building the engine, so installing the same version did the trick. The "_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR" define also works, but I'm opting for the correct solution here. Thanks a lot for the help!
