### ISSUE TITLE
Windows executable (astcenc.exe) runs at High priority causing entire computer to freeze

### ISSUE THREAD

**Issue by guygodin** [ARM-software/astc-encoder#69]
The astcenc executable has its process priority to High by default causing any lengthy encoding to lock up Windows. A higher priority doesn't make it run any faster, it just prevents other programs from working correctly.

**Comment by solidpixel** [comment]
How are you running the encoder?

We never set thread priorities anywhere in the code, so this should be a "normal" priority process and thread pool unless it's being invoked by another process which is increasing the priority (or you've manually set the priority and saved it persistently, which Windows allows).

**Comment by guygodin** [comment]
Hi, sorry, I should have looked more closely. astcenc.exe is ran by PVRTexTool, which are probably increasing the process priority. I have reached out to them but received no response. I will try again. Thanks for your time!
