### ISSUE TITLE
Duplicated code?

### ISSUE THREAD

**Issue by Kirpich30000** [ARM-software/astc-encoder#7]
Is there any reason to convert symbolic compressed block to physical compressed block and back again at the [end of compress_symbolic_block()](https://github.com/ARM-software/astc-encoder/blob/437f2423fede947a09086f28f547d1897bfe4546/Source/astc_compress_symbolic.cpp#L1800-1801)? Will it differs from original scb?

Anyway, right after that scb->pcb->scb convertion [it would be again converted](https://github.com/ARM-software/astc-encoder/blob/437f2423fede947a09086f28f547d1897bfe4546/Source/astc_toplevel.cpp#L351-361) scb->pcb in case of !pack_and_unpack , and just decompressed otherwise. Is it safe just to delete [those two lines](https://github.com/ARM-software/astc-encoder/blob/437f2423fede947a09086f28f547d1897bfe4546/Source/astc_compress_symbolic.cpp#L1800-1801)

**Comment by NikunjPatel-ARM** [comment]
A quick test shows that a symbolic block converted a physical block and back again may or may not be the same as the original symbolic block, depending on the compression mode that gets used for the block.

You should be able to see from the code in symbolic_to_physical that some quantization is done on the weights for certain compression modes that irreversibly loses data from the original symbolic block.

Therefore, it is not safe to delete the two lines.

After this initial lossy conversion, another conversion from symbolic->physical->symbolic should always (barring any strange edge cases) result in the same symbolic block being generated.

You are correct that for the non "pack_and_unpack" case, there is a redundant symbolic_to_physical conversion. However, the cost of this conversion is negligible compared to the overall cost of the compression, so it isn't worth the effort to refactor the code to prevent this from happening.
