### ISSUE TITLE
fix variables shadowing

### ISSUE THREAD

**Issue by renato-grottesi** [ARM-software/astc-encoder#70]
I'm getting compilation -Werror=shadow errors on GCC 7.4.0

**Comment by solidpixel** [comment]
Related - looking though some of the existing shadows there is some "weird" behavior here. For example: `quant_mod` here is only modified in an inner (shadowed) scope in the block above, so this one will always be zero. 

https://github.com/ARM-software/astc-encoder/blob/master/Source/astc_ideal_endpoints_and_weights.cpp#L1428
