### ISSUE TITLE
Thread objects leak (win32)

### ISSUE THREAD

**Issue by lmveilleux** [ARM-software/astc-encoder#71]
In `astc_toplevel.cpp`, the call to `CreateThread` at line 50 is missing its matching `CloseHandle` call, causing the created thread objects to leak. I propose adding the missing call in `pthread_join`, like so:

```cpp
	int pthread_join(pthread_t thread, void **value)
	{
		WaitForSingleObject(thread, INFINITE);
		CloseHandle(thread); // <= Missing
		return 0;
	}
```

**Comment by solidpixel** [comment]
Thanks for the bug report.

**Comment by lmveilleux** [comment]
You're welcome :)
