### ISSUE TITLE
Support compressing mipmap chains

### ISSUE THREAD

**Issue by solidpixel** [ARM-software/astc-encoder#74]
A common developer need is to compress entire mipmap chains. Currently `astcenc` cannot do that; you have to compress single mip levels and then repack them as a post-process activity. This issue looks at adding mipmap support for compression and decompression.

For compression workflows:

* Mipmap generation
* Mipmap compression
* Storage as a KTX format output. 

For decompression workflows:

* Storage as any uncompressed format, with a "_level<N>" postfix.

### Mipmap generation

The most interesting part of this issue is the mipmap generation, as there are multiple aspects to consider.

What filters to expose?

* Weighted box filer with bilinear sample weighting for odd sizes.
* Box with random sample (useful for e.g. noise textures, where you want to preserve dynamic range and frequency and not low-pass filter the noise)
* N-sample lanczos.
* N-sample kaiser.
* For windowed filters support filtering wraps for tiled textures.

What tweaks to apply?

* Always downsample from original vs downsample from level N-1? In principal downsampling from the original each time avoids accumulating error from each level's approximation for e.g. lanczos filter windows.
* sRGB - filter in linear space to preserve gamma intensity.
* Normals - renormalize each level.

**Comment by claurel** [comment]
I've implemented mipmap generation and KTX export in my private branch of astcenc. I'd be happy to contribute my changes, but there's one shortcoming with my implementation: it doesn't support 3d mipmaps, and I don't have the time available to do it. Is it still of interest? I can certainly understand where you'd only want to accept contributed code that supports the full set of ASTC formats.

**Comment by solidpixel** [comment]
This is now possible via the Khronos `toktx` utility, so at the moment there is no plan to add support for this here. Closing.
