### ISSUE TITLE
Support KTX as compressor output format and decompressor input format

### ISSUE THREAD

**Issue by Ben-Mack** [ARM-software/astc-encoder#75]
Currently the only output compressed format of astc-encoder is ASTC format.
I can't find any way to convert from ASTC to KTX.

Please add support for KTX format as it's more widely used, almost all other compressor support KTX as output format.

How can I convert ASTC to KTX (without decompressed it)?

**Comment by wasimabbas-arm** [comment]
@Ben-Mack https://github.com/ARM-software/ktx-creator just created a special repo for you :) enjoy!

**Comment by Ben-Mack** [comment]
@wasimabbas-arm Huge thank for the repo!

ktx-creator run fine on PNG file, but not .astc file.
Here's the error dialog when I tried to run ktx-creator on .astc file (compressed beforehand by astcenc):
```
ktx-creator compressed.astc
```
![Annotation 2020-01-07 202055](https://user-images.githubusercontent.com/6309393/71898182-3d7c6880-318b-11ea-8fce-0f5a17e7a8dd.png)

**Comment by wasimabbas-arm** [comment]
Interesting. I don't think we have implemented ASTC support into the compressor. It will create the ASTC from PNG etc for you.
Happy to accept contributions if you can short circuit the PNG route and go straight to KTX creation.

**Comment by Fahien** [comment]
Hi there!

The main function does not support this flow yet, but it can be easily implemented as the codebase already supports that. If you have a look at [ktx_test.cpp:21](https://github.com/ARM-software/ktx-creator/blob/master/test/src/ktx_test.cpp#L21), there is a test section named `Can create ktx from astc` which shows how it is done!

**Comment by solidpixel** [comment]
PR to add this: https://github.com/ARM-software/astc-encoder/pull/127

No mipmap generation; this exports a single compressed surface (2D or 3D) image wrapped in KTX.

**Comment by solidpixel** [comment]
Merged
