### ISSUE TITLE
Support KTX as output format

### ISSUE THREAD

**Issue by SMalls0098** [ARM-software/astc-encoder#87]
Last time I saw a warehouse that supported ktx, but now it seems to be 404. I can't enter it.

**Comment by wasimabbas-arm** [comment]
I am aware, I will update here when I uploaded it.

**Comment by SMalls0098** [comment]
thanks

**Comment by SMalls0098** [comment]
May I ask the exact time?

**Comment by wasimabbas-arm** [comment]
Early next week. Monday or Tuesday by the latest. Sorry for delay.

**Comment by wasimabbas-arm** [comment]
Here is the software you can use to create KTX files with ASTC support. 
https://github.com/ARM-software/ktx-creator
