### ISSUE TITLE
Binary not available in MAC os

### ISSUE THREAD

**Issue by vaibhavgupta-bst** [ARM-software/astc-encoder#90]
I am able to use the binary ./astcenc as i am not able to get the Binary repository.
Kindly help.

**Comment by solidpixel** [comment]
As per the documentation in the README:

> Prebuilt release build binaries of astcenc for 64-bit Linux, macOS, and Windows are available in the GitHub Releases page. Note that currently no 2.x series pre-built binaries are available.

This is the latest macOS release:

https://github.com/ARM-software/astc-encoder/releases/download/1.7/astcenc-1.7-macos-x64.zip

**Comment by vaibhavgupta-bst** [comment]
Hey @solidpixel , I had changed the code in toplevel.cpp and i was able to build it but how can i generate the binary to test it at runtime?

**Comment by solidpixel** [comment]
Sorry - I'm still not entirely sure what problem you are having. What are you trying to do? What commands are you using? And what's not working?

**Comment by vaibhavgupta-bst** [comment]
I am using MAC build, and i have changed the code a bit. Now i am able to correctly build the Source using  make command but ./astcenc is not generated so that i can use the binary to decompress the image

**Comment by solidpixel** [comment]
On `master` using an unmodified Makefile the binaries are suffixed by the SIMD feature set used. e.g. the default builds are for the AVX2 instruction set - the binary for this will be called `astcenc-avx2`. 

If you want to compile for SSE2 compile for using "make VEC=sse2" - the binary will be called `astcenc-sse2`.

If you want to compile for SSE4.2 compile using "make VEC=sse4.2" - the binary will be called `astcenc-sse4.2`

**Comment by solidpixel** [comment]
See: https://github.com/ARM-software/astc-encoder/blob/master/Docs/Building.md
